org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
fabric.loom.disableObfuscation=true
primeShaderFullDebug=true
primeSlangVersion=2026.13.1-1-g84792eb15
primeSpirvToolsVersions=SPIRV-Tools v2026.3 v2026.3.rc1-0-gb707790a|SPIRV-Tools v2026.3 v2026.3.rc1-1-g9a49b088

minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17.14
fabric_api_version=0.154.2+26.2

mod_version=1.4.0
maven_group=dev.prime
archives_base_name=prime
