package dev.prime.binding.streamline;

/** sl::BufferType (uint32_t) */
public enum BufferType {
    DEPTH(0),
    MOTION_VECTORS(1),
    HUD_LESS_COLOR(2),
    SCALING_INPUT_COLOR(3),
    SCALING_OUTPUT_COLOR(4),
    NORMALS(5),
    ROUGHNESS(6),
    ALBEDO(7),
    SPECULAR_ALBEDO(8),
    INDIRECT_ALBEDO(9),
    SPECULAR_MOTION_VECTORS(10),
    DISOCCLUSION_MASK(11),
    EMISSIVE(12),
    EXPOSURE(13),
    NORMAL_ROUGHNESS(14),
    DIFFUSE_HIT_NOISY(15),
    DIFFUSE_HIT_DENOISED(16),
    SPECULAR_HIT_NOISY(17),
    SPECULAR_HIT_DENOISED(18),
    SHADOW_NOISY(19),
    SHADOW_DENOISED(20),
    AMBIENT_OCCLUSION_NOISY(21),
    AMBIENT_OCCLUSION_DENOISED(22),
    UI_COLOR_AND_ALPHA(23),
    SHADOW_HINT(24),
    REFLECTION_HINT(25),
    PARTICLE_HINT(26),
    TRANSPARENCY_HINT(27),
    ANIMATED_TEXTURE_HINT(28),
    BIAS_CURRENT_COLOR_HINT(29),
    RAYTRACING_DISTANCE(30),
    REFLECTION_MOTION_VECTORS(31),
    POSITION(32),
    INVALID_DEPTH_MOTION_HINT(33),
    ALPHA(34),
    OPAQUE_COLOR(35),
    REACTIVE_MASK_HINT(36),
    TRANSPARENCY_AND_COMPOSITION_MASK_HINT(37),
    REFLECTED_ALBEDO(38),
    COLOR_BEFORE_PARTICLES(39),
    COLOR_BEFORE_TRANSPARENCY(40),
    COLOR_BEFORE_FOG(41),
    SPECULAR_HIT_DISTANCE(42),
    SPECULAR_RAY_DIRECTION_HIT_DISTANCE(43),
    SPECULAR_RAY_DIRECTION(44),
    DIFFUSE_HIT_DISTANCE(45),
    DIFFUSE_RAY_DIRECTION_HIT_DISTANCE(46),
    DIFFUSE_RAY_DIRECTION(47),
    HI_RES_DEPTH(48),
    LINEAR_DEPTH(49),
    BIDIRECTIONAL_DISTORTION_FIELD(50),
    TRANSPARENCY_LAYER(51),
    TRANSPARENCY_LAYER_OPACITY(52),
    BACKBUFFER(53),
    NO_WARP_MASK(54),
    COLOR_AFTER_PARTICLES(55),
    COLOR_AFTER_TRANSPARENCY(56),
    COLOR_AFTER_FOG(57),
    SCREEN_SPACE_SUBSURFACE_SCATTERING_GUIDE(58),
    COLOR_BEFORE_SCREEN_SPACE_SUBSURFACE_SCATTERING(59),
    COLOR_AFTER_SCREEN_SPACE_SUBSURFACE_SCATTERING(60),
    SCREEN_SPACE_REFRACTION_GUIDE(61),
    COLOR_BEFORE_SCREEN_SPACE_REFRACTION(62),
    COLOR_AFTER_SCREEN_SPACE_REFRACTION(63),
    DEPTH_OF_FIELD_GUIDE(64),
    COLOR_BEFORE_DEPTH_OF_FIELD(65),
    COLOR_AFTER_DEPTH_OF_FIELD(66),
    SCALING_OUTPUT_ALPHA(67),
    RESPONSIVITY_MASK(68),
    UI_ALPHA(69);

    public final int value;

    BufferType(int value) {
        this.value = value;
    }

    public static BufferType fromValue(int value) {
        for (BufferType type : values()) {
            if (type.value == value) {
                return type;
            }
        }
        throw new IllegalArgumentException("Unknown sl::BufferType value: " + value);
    }
}
