// Generated by scripts/generate-abi.py; edit C headers, not this file.
// Uniform explicit defaults also support fixed arrays larger than Rust Default derives.
#![allow(clippy::derivable_impls)]
pub const PRIME_ABI_VERSION: u32 = 9;
pub const PRIME_MAX_BATCH_BYTES: u32 = 268435456;
pub const PRIME_HOST_OMM: u32 = 1;
pub const PRIME_HOST_STREAMLINE: u32 = 2;
pub const PRIME_STREAMLINE_BEGIN_FRAME: u32 = 0;
pub const PRIME_STREAMLINE_RENDER_START: u32 = 1;
pub const PRIME_STREAMLINE_RENDER_END: u32 = 2;
pub const PRIME_STREAMLINE_SUSPEND: u32 = 3;
pub const PRIME_STREAMLINE_HOST_SHUTDOWN: u32 = 4;
pub const PRIME_MC_SOURCE_VERSION: u32 = 7;
pub const PRIME_MC_RESOURCE_REPLACE: u32 = 1;

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeHeader {
    pub struct_size: u32,
    pub abi_version: u32,
}
impl Default for PrimeHeader {
    fn default() -> Self {
        Self {
            struct_size: 0,
            abi_version: 0,
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeHeader>() == 8);
const _: () = assert!(std::mem::align_of::<PrimeHeader>() == 4);
const _: () = assert!(std::mem::offset_of!(PrimeHeader, struct_size) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeHeader, abi_version) == 4);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeByteSpan {
    pub data: *const u8,
    pub count: u64,
}
impl Default for PrimeByteSpan {
    fn default() -> Self {
        Self {
            data: std::ptr::null(),
            count: 0,
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeByteSpan>() == 16);
const _: () = assert!(std::mem::align_of::<PrimeByteSpan>() == 8);
const _: () = assert!(std::mem::offset_of!(PrimeByteSpan, data) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeByteSpan, count) == 8);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeU32Span {
    pub data: *const u32,
    pub count: u64,
}
impl Default for PrimeU32Span {
    fn default() -> Self {
        Self {
            data: std::ptr::null(),
            count: 0,
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeU32Span>() == 16);
const _: () = assert!(std::mem::align_of::<PrimeU32Span>() == 8);
const _: () = assert!(std::mem::offset_of!(PrimeU32Span, data) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeU32Span, count) == 8);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeU64Span {
    pub data: *const u64,
    pub count: u64,
}
impl Default for PrimeU64Span {
    fn default() -> Self {
        Self {
            data: std::ptr::null(),
            count: 0,
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeU64Span>() == 16);
const _: () = assert!(std::mem::align_of::<PrimeU64Span>() == 8);
const _: () = assert!(std::mem::offset_of!(PrimeU64Span, data) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeU64Span, count) == 8);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeReset {
    pub header: PrimeHeader,
    pub epoch: u64,
}
impl Default for PrimeReset {
    fn default() -> Self {
        Self {
            header: PrimeHeader::default(),
            epoch: 0,
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeReset>() == 16);
const _: () = assert!(std::mem::align_of::<PrimeReset>() == 8);
const _: () = assert!(std::mem::offset_of!(PrimeReset, header) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeReset, epoch) == 8);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeFrame {
    pub header: PrimeHeader,
    pub epoch: u64,
    pub position: [f64; 3],
    pub forward: [f32; 3],
    pub right: [f32; 3],
    pub up: [f32; 3],
    pub fov_y: f32,
    pub width: u32,
    pub height: u32,
    pub sample_index: u32,
    pub solar_hour_angle: f32,
}
impl Default for PrimeFrame {
    fn default() -> Self {
        Self {
            header: PrimeHeader::default(),
            epoch: 0,
            position: [0.0; 3],
            forward: [0.0; 3],
            right: [0.0; 3],
            up: [0.0; 3],
            fov_y: 0.0,
            width: 0,
            height: 0,
            sample_index: 0,
            solar_hour_angle: 0.0,
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeFrame>() == 96);
const _: () = assert!(std::mem::align_of::<PrimeFrame>() == 8);
const _: () = assert!(std::mem::offset_of!(PrimeFrame, header) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeFrame, epoch) == 8);
const _: () = assert!(std::mem::offset_of!(PrimeFrame, position) == 16);
const _: () = assert!(std::mem::offset_of!(PrimeFrame, forward) == 40);
const _: () = assert!(std::mem::offset_of!(PrimeFrame, right) == 52);
const _: () = assert!(std::mem::offset_of!(PrimeFrame, up) == 64);
const _: () = assert!(std::mem::offset_of!(PrimeFrame, fov_y) == 76);
const _: () = assert!(std::mem::offset_of!(PrimeFrame, width) == 80);
const _: () = assert!(std::mem::offset_of!(PrimeFrame, height) == 84);
const _: () = assert!(std::mem::offset_of!(PrimeFrame, sample_index) == 88);
const _: () = assert!(std::mem::offset_of!(PrimeFrame, solar_hour_angle) == 92);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeSettings {
    pub header: PrimeHeader,
    pub mode: u32,
    pub bounces: u32,
    pub offline_samples: u32,
    pub exposure: f32,
    pub hue: f32,
    pub saturation: f32,
    pub view: u32,
    pub sun: f32,
    pub sky: f32,
    pub depth_range: f32,
    pub seed: u32,
    pub latitude_degrees: i32,
    pub solar_longitude_degrees: u32,
    pub opacity_micromap: u32,
    pub ray_reconstruction: u32,
    pub reconstruction_quality: u32,
    pub terrain_batches_per_frame: u32,
    pub stars: f32,
    pub auto_exposure_compensation: f32,
    pub hdr: u32,
    pub hdr_reference_white: u32,
    pub frame_generation: u32,
}
impl Default for PrimeSettings {
    fn default() -> Self {
        Self {
            header: PrimeHeader::default(),
            mode: 0,
            bounces: 0,
            offline_samples: 0,
            exposure: 0.0,
            hue: 0.0,
            saturation: 0.0,
            view: 0,
            sun: 0.0,
            sky: 0.0,
            depth_range: 0.0,
            seed: 0,
            latitude_degrees: 0,
            solar_longitude_degrees: 0,
            opacity_micromap: 0,
            ray_reconstruction: 0,
            reconstruction_quality: 0,
            terrain_batches_per_frame: 0,
            stars: 0.0,
            auto_exposure_compensation: 0.0,
            hdr: 0,
            hdr_reference_white: 0,
            frame_generation: 0,
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeSettings>() == 96);
const _: () = assert!(std::mem::align_of::<PrimeSettings>() == 4);
const _: () = assert!(std::mem::offset_of!(PrimeSettings, header) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeSettings, mode) == 8);
const _: () = assert!(std::mem::offset_of!(PrimeSettings, bounces) == 12);
const _: () = assert!(std::mem::offset_of!(PrimeSettings, offline_samples) == 16);
const _: () = assert!(std::mem::offset_of!(PrimeSettings, exposure) == 20);
const _: () = assert!(std::mem::offset_of!(PrimeSettings, hue) == 24);
const _: () = assert!(std::mem::offset_of!(PrimeSettings, saturation) == 28);
const _: () = assert!(std::mem::offset_of!(PrimeSettings, view) == 32);
const _: () = assert!(std::mem::offset_of!(PrimeSettings, sun) == 36);
const _: () = assert!(std::mem::offset_of!(PrimeSettings, sky) == 40);
const _: () = assert!(std::mem::offset_of!(PrimeSettings, depth_range) == 44);
const _: () = assert!(std::mem::offset_of!(PrimeSettings, seed) == 48);
const _: () = assert!(std::mem::offset_of!(PrimeSettings, latitude_degrees) == 52);
const _: () = assert!(std::mem::offset_of!(PrimeSettings, solar_longitude_degrees) == 56);
const _: () = assert!(std::mem::offset_of!(PrimeSettings, opacity_micromap) == 60);
const _: () = assert!(std::mem::offset_of!(PrimeSettings, ray_reconstruction) == 64);
const _: () = assert!(std::mem::offset_of!(PrimeSettings, reconstruction_quality) == 68);
const _: () = assert!(std::mem::offset_of!(PrimeSettings, terrain_batches_per_frame) == 72);
const _: () = assert!(std::mem::offset_of!(PrimeSettings, stars) == 76);
const _: () = assert!(std::mem::offset_of!(PrimeSettings, auto_exposure_compensation) == 80);
const _: () = assert!(std::mem::offset_of!(PrimeSettings, hdr) == 84);
const _: () = assert!(std::mem::offset_of!(PrimeSettings, hdr_reference_white) == 88);
const _: () = assert!(std::mem::offset_of!(PrimeSettings, frame_generation) == 92);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeVulkanHost {
    pub header: PrimeHeader,
    pub instance: u64,
    pub physical_device: u64,
    pub device: u64,
    pub queue: u64,
    pub timeline: u64,
    pub queue_family: u32,
    pub capabilities: u32,
}
impl Default for PrimeVulkanHost {
    fn default() -> Self {
        Self {
            header: PrimeHeader::default(),
            instance: 0,
            physical_device: 0,
            device: 0,
            queue: 0,
            timeline: 0,
            queue_family: 0,
            capabilities: 0,
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeVulkanHost>() == 56);
const _: () = assert!(std::mem::align_of::<PrimeVulkanHost>() == 8);
const _: () = assert!(std::mem::offset_of!(PrimeVulkanHost, header) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeVulkanHost, instance) == 8);
const _: () = assert!(std::mem::offset_of!(PrimeVulkanHost, physical_device) == 16);
const _: () = assert!(std::mem::offset_of!(PrimeVulkanHost, device) == 24);
const _: () = assert!(std::mem::offset_of!(PrimeVulkanHost, queue) == 32);
const _: () = assert!(std::mem::offset_of!(PrimeVulkanHost, timeline) == 40);
const _: () = assert!(std::mem::offset_of!(PrimeVulkanHost, queue_family) == 48);
const _: () = assert!(std::mem::offset_of!(PrimeVulkanHost, capabilities) == 52);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeRecordTarget {
    pub header: PrimeHeader,
    pub command: u64,
    pub image: u64,
    pub view: u64,
    pub serial: u64,
}
impl Default for PrimeRecordTarget {
    fn default() -> Self {
        Self {
            header: PrimeHeader::default(),
            command: 0,
            image: 0,
            view: 0,
            serial: 0,
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeRecordTarget>() == 40);
const _: () = assert!(std::mem::align_of::<PrimeRecordTarget>() == 8);
const _: () = assert!(std::mem::offset_of!(PrimeRecordTarget, header) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeRecordTarget, command) == 8);
const _: () = assert!(std::mem::offset_of!(PrimeRecordTarget, image) == 16);
const _: () = assert!(std::mem::offset_of!(PrimeRecordTarget, view) == 24);
const _: () = assert!(std::mem::offset_of!(PrimeRecordTarget, serial) == 32);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeDisplayOutput {
    pub header: PrimeHeader,
    pub active: u32,
    pub peak_nits: f32,
    pub system_white_nits: f32,
    pub reserved: u32,
}
impl Default for PrimeDisplayOutput {
    fn default() -> Self {
        Self {
            header: PrimeHeader::default(),
            active: 0,
            peak_nits: 0.0,
            system_white_nits: 0.0,
            reserved: 0,
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeDisplayOutput>() == 24);
const _: () = assert!(std::mem::align_of::<PrimeDisplayOutput>() == 4);
const _: () = assert!(std::mem::offset_of!(PrimeDisplayOutput, header) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeDisplayOutput, active) == 8);
const _: () = assert!(std::mem::offset_of!(PrimeDisplayOutput, peak_nits) == 12);
const _: () = assert!(std::mem::offset_of!(PrimeDisplayOutput, system_white_nits) == 16);
const _: () = assert!(std::mem::offset_of!(PrimeDisplayOutput, reserved) == 20);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeHdrTarget {
    pub header: PrimeHeader,
    pub command: u64,
    pub ui_image: u64,
    pub ui_view: u64,
    pub output_image: u64,
    pub output_view: u64,
    pub serial: u64,
    pub width: u32,
    pub height: u32,
}
impl Default for PrimeHdrTarget {
    fn default() -> Self {
        Self {
            header: PrimeHeader::default(),
            command: 0,
            ui_image: 0,
            ui_view: 0,
            output_image: 0,
            output_view: 0,
            serial: 0,
            width: 0,
            height: 0,
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeHdrTarget>() == 64);
const _: () = assert!(std::mem::align_of::<PrimeHdrTarget>() == 8);
const _: () = assert!(std::mem::offset_of!(PrimeHdrTarget, header) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeHdrTarget, command) == 8);
const _: () = assert!(std::mem::offset_of!(PrimeHdrTarget, ui_image) == 16);
const _: () = assert!(std::mem::offset_of!(PrimeHdrTarget, ui_view) == 24);
const _: () = assert!(std::mem::offset_of!(PrimeHdrTarget, output_image) == 32);
const _: () = assert!(std::mem::offset_of!(PrimeHdrTarget, output_view) == 40);
const _: () = assert!(std::mem::offset_of!(PrimeHdrTarget, serial) == 48);
const _: () = assert!(std::mem::offset_of!(PrimeHdrTarget, width) == 56);
const _: () = assert!(std::mem::offset_of!(PrimeHdrTarget, height) == 60);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimePrepareResources {
    pub header: PrimeHeader,
    pub command: u64,
    pub serial: u64,
}
impl Default for PrimePrepareResources {
    fn default() -> Self {
        Self {
            header: PrimeHeader::default(),
            command: 0,
            serial: 0,
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimePrepareResources>() == 24);
const _: () = assert!(std::mem::align_of::<PrimePrepareResources>() == 8);
const _: () = assert!(std::mem::offset_of!(PrimePrepareResources, header) == 0);
const _: () = assert!(std::mem::offset_of!(PrimePrepareResources, command) == 8);
const _: () = assert!(std::mem::offset_of!(PrimePrepareResources, serial) == 16);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeTextureSource {
    pub id: u32,
    pub width: u32,
    pub height: u32,
    pub reserved: u32,
    pub rgba: PrimeByteSpan,
}
impl Default for PrimeTextureSource {
    fn default() -> Self {
        Self {
            id: 0,
            width: 0,
            height: 0,
            reserved: 0,
            rgba: PrimeByteSpan::default(),
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeTextureSource>() == 32);
const _: () = assert!(std::mem::align_of::<PrimeTextureSource>() == 8);
const _: () = assert!(std::mem::offset_of!(PrimeTextureSource, id) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeTextureSource, width) == 4);
const _: () = assert!(std::mem::offset_of!(PrimeTextureSource, height) == 8);
const _: () = assert!(std::mem::offset_of!(PrimeTextureSource, reserved) == 12);
const _: () = assert!(std::mem::offset_of!(PrimeTextureSource, rgba) == 16);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeTextureBatch {
    pub header: PrimeHeader,
    pub epoch: u64,
    pub textures: *const PrimeTextureSource,
    pub count: u64,
}
impl Default for PrimeTextureBatch {
    fn default() -> Self {
        Self {
            header: PrimeHeader::default(),
            epoch: 0,
            textures: std::ptr::null(),
            count: 0,
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeTextureBatch>() == 32);
const _: () = assert!(std::mem::align_of::<PrimeTextureBatch>() == 8);
const _: () = assert!(std::mem::offset_of!(PrimeTextureBatch, header) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeTextureBatch, epoch) == 8);
const _: () = assert!(std::mem::offset_of!(PrimeTextureBatch, textures) == 16);
const _: () = assert!(std::mem::offset_of!(PrimeTextureBatch, count) == 24);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeTextureRetire {
    pub header: PrimeHeader,
    pub epoch: u64,
    pub ids: PrimeU32Span,
}
impl Default for PrimeTextureRetire {
    fn default() -> Self {
        Self {
            header: PrimeHeader::default(),
            epoch: 0,
            ids: PrimeU32Span::default(),
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeTextureRetire>() == 32);
const _: () = assert!(std::mem::align_of::<PrimeTextureRetire>() == 8);
const _: () = assert!(std::mem::offset_of!(PrimeTextureRetire, header) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeTextureRetire, epoch) == 8);
const _: () = assert!(std::mem::offset_of!(PrimeTextureRetire, ids) == 16);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeMeshSpan {
    pub texture_id: u32,
    pub flags: u32,
    pub topology: u32,
    pub vertex_count: u32,
    pub stride: u32,
    pub position_offset: u32,
    pub color_offset: u32,
    pub uv_offset: u32,
    pub vertices: PrimeByteSpan,
}
impl Default for PrimeMeshSpan {
    fn default() -> Self {
        Self {
            texture_id: 0,
            flags: 0,
            topology: 0,
            vertex_count: 0,
            stride: 0,
            position_offset: 0,
            color_offset: 0,
            uv_offset: 0,
            vertices: PrimeByteSpan::default(),
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeMeshSpan>() == 48);
const _: () = assert!(std::mem::align_of::<PrimeMeshSpan>() == 8);
const _: () = assert!(std::mem::offset_of!(PrimeMeshSpan, texture_id) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeMeshSpan, flags) == 4);
const _: () = assert!(std::mem::offset_of!(PrimeMeshSpan, topology) == 8);
const _: () = assert!(std::mem::offset_of!(PrimeMeshSpan, vertex_count) == 12);
const _: () = assert!(std::mem::offset_of!(PrimeMeshSpan, stride) == 16);
const _: () = assert!(std::mem::offset_of!(PrimeMeshSpan, position_offset) == 20);
const _: () = assert!(std::mem::offset_of!(PrimeMeshSpan, color_offset) == 24);
const _: () = assert!(std::mem::offset_of!(PrimeMeshSpan, uv_offset) == 28);
const _: () = assert!(std::mem::offset_of!(PrimeMeshSpan, vertices) == 32);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeBillboard {
    pub position: [f32; 3],
    pub quaternion: [f32; 4],
    pub scale: f32,
    pub uv: [f32; 4],
    pub rgba: u32,
}
impl Default for PrimeBillboard {
    fn default() -> Self {
        Self {
            position: [0.0; 3],
            quaternion: [0.0; 4],
            scale: 0.0,
            uv: [0.0; 4],
            rgba: 0,
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeBillboard>() == 52);
const _: () = assert!(std::mem::align_of::<PrimeBillboard>() == 4);
const _: () = assert!(std::mem::offset_of!(PrimeBillboard, position) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeBillboard, quaternion) == 12);
const _: () = assert!(std::mem::offset_of!(PrimeBillboard, scale) == 28);
const _: () = assert!(std::mem::offset_of!(PrimeBillboard, uv) == 32);
const _: () = assert!(std::mem::offset_of!(PrimeBillboard, rgba) == 48);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeDynamicBatch {
    pub header: PrimeHeader,
    pub epoch: u64,
    pub sequence: u64,
    pub origin: [f64; 3],
    pub spans: *const PrimeMeshSpan,
    pub count: u64,
}
impl Default for PrimeDynamicBatch {
    fn default() -> Self {
        Self {
            header: PrimeHeader::default(),
            epoch: 0,
            sequence: 0,
            origin: [0.0; 3],
            spans: std::ptr::null(),
            count: 0,
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeDynamicBatch>() == 64);
const _: () = assert!(std::mem::align_of::<PrimeDynamicBatch>() == 8);
const _: () = assert!(std::mem::offset_of!(PrimeDynamicBatch, header) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeDynamicBatch, epoch) == 8);
const _: () = assert!(std::mem::offset_of!(PrimeDynamicBatch, sequence) == 16);
const _: () = assert!(std::mem::offset_of!(PrimeDynamicBatch, origin) == 24);
const _: () = assert!(std::mem::offset_of!(PrimeDynamicBatch, spans) == 48);
const _: () = assert!(std::mem::offset_of!(PrimeDynamicBatch, count) == 56);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimePrototypeSource {
    pub id: u64,
    pub revision: u64,
    pub spans: *const PrimeMeshSpan,
    pub count: u64,
}
impl Default for PrimePrototypeSource {
    fn default() -> Self {
        Self {
            id: 0,
            revision: 0,
            spans: std::ptr::null(),
            count: 0,
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimePrototypeSource>() == 32);
const _: () = assert!(std::mem::align_of::<PrimePrototypeSource>() == 8);
const _: () = assert!(std::mem::offset_of!(PrimePrototypeSource, id) == 0);
const _: () = assert!(std::mem::offset_of!(PrimePrototypeSource, revision) == 8);
const _: () = assert!(std::mem::offset_of!(PrimePrototypeSource, spans) == 16);
const _: () = assert!(std::mem::offset_of!(PrimePrototypeSource, count) == 24);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeRemoval {
    pub id: u64,
    pub revision: u64,
}
impl Default for PrimeRemoval {
    fn default() -> Self {
        Self { id: 0, revision: 0 }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeRemoval>() == 16);
const _: () = assert!(std::mem::align_of::<PrimeRemoval>() == 8);
const _: () = assert!(std::mem::offset_of!(PrimeRemoval, id) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeRemoval, revision) == 8);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeInstanceSource {
    pub id: u64,
    pub revision: u64,
    pub prototype_id: u64,
    pub origin: [f64; 3],
    pub transform: [f32; 12],
    pub texture_id: u32,
    pub flags: u32,
    pub rgba: u32,
    pub reserved: u32,
    pub uv_transform: [f32; 4],
}
impl Default for PrimeInstanceSource {
    fn default() -> Self {
        Self {
            id: 0,
            revision: 0,
            prototype_id: 0,
            origin: [0.0; 3],
            transform: [0.0; 12],
            texture_id: 0,
            flags: 0,
            rgba: 0,
            reserved: 0,
            uv_transform: [0.0; 4],
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeInstanceSource>() == 128);
const _: () = assert!(std::mem::align_of::<PrimeInstanceSource>() == 8);
const _: () = assert!(std::mem::offset_of!(PrimeInstanceSource, id) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeInstanceSource, revision) == 8);
const _: () = assert!(std::mem::offset_of!(PrimeInstanceSource, prototype_id) == 16);
const _: () = assert!(std::mem::offset_of!(PrimeInstanceSource, origin) == 24);
const _: () = assert!(std::mem::offset_of!(PrimeInstanceSource, transform) == 48);
const _: () = assert!(std::mem::offset_of!(PrimeInstanceSource, texture_id) == 96);
const _: () = assert!(std::mem::offset_of!(PrimeInstanceSource, flags) == 100);
const _: () = assert!(std::mem::offset_of!(PrimeInstanceSource, rgba) == 104);
const _: () = assert!(std::mem::offset_of!(PrimeInstanceSource, reserved) == 108);
const _: () = assert!(std::mem::offset_of!(PrimeInstanceSource, uv_transform) == 112);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeInstanceBatch {
    pub header: PrimeHeader,
    pub epoch: u64,
    pub sequence: u64,
    pub prototypes: *const PrimePrototypeSource,
    pub prototype_count: u64,
    pub prototype_removals: *const PrimeRemoval,
    pub prototype_removal_count: u64,
    pub instances: *const PrimeInstanceSource,
    pub instance_count: u64,
    pub instance_removals: *const PrimeRemoval,
    pub instance_removal_count: u64,
}
impl Default for PrimeInstanceBatch {
    fn default() -> Self {
        Self {
            header: PrimeHeader::default(),
            epoch: 0,
            sequence: 0,
            prototypes: std::ptr::null(),
            prototype_count: 0,
            prototype_removals: std::ptr::null(),
            prototype_removal_count: 0,
            instances: std::ptr::null(),
            instance_count: 0,
            instance_removals: std::ptr::null(),
            instance_removal_count: 0,
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeInstanceBatch>() == 88);
const _: () = assert!(std::mem::align_of::<PrimeInstanceBatch>() == 8);
const _: () = assert!(std::mem::offset_of!(PrimeInstanceBatch, header) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeInstanceBatch, epoch) == 8);
const _: () = assert!(std::mem::offset_of!(PrimeInstanceBatch, sequence) == 16);
const _: () = assert!(std::mem::offset_of!(PrimeInstanceBatch, prototypes) == 24);
const _: () = assert!(std::mem::offset_of!(PrimeInstanceBatch, prototype_count) == 32);
const _: () = assert!(std::mem::offset_of!(PrimeInstanceBatch, prototype_removals) == 40);
const _: () = assert!(std::mem::offset_of!(PrimeInstanceBatch, prototype_removal_count) == 48);
const _: () = assert!(std::mem::offset_of!(PrimeInstanceBatch, instances) == 56);
const _: () = assert!(std::mem::offset_of!(PrimeInstanceBatch, instance_count) == 64);
const _: () = assert!(std::mem::offset_of!(PrimeInstanceBatch, instance_removals) == 72);
const _: () = assert!(std::mem::offset_of!(PrimeInstanceBatch, instance_removal_count) == 80);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeMcIdentity {
    pub struct_size: u32,
    pub abi_version: u32,
    pub source_version: u32,
    pub game_version: u32,
    pub resource_generation: u64,
    pub epoch: u64,
    pub batch: u64,
}
impl Default for PrimeMcIdentity {
    fn default() -> Self {
        Self {
            struct_size: 0,
            abi_version: 0,
            source_version: 0,
            game_version: 0,
            resource_generation: 0,
            epoch: 0,
            batch: 0,
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeMcIdentity>() == 40);
const _: () = assert!(std::mem::align_of::<PrimeMcIdentity>() == 8);
const _: () = assert!(std::mem::offset_of!(PrimeMcIdentity, struct_size) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeMcIdentity, abi_version) == 4);
const _: () = assert!(std::mem::offset_of!(PrimeMcIdentity, source_version) == 8);
const _: () = assert!(std::mem::offset_of!(PrimeMcIdentity, game_version) == 12);
const _: () = assert!(std::mem::offset_of!(PrimeMcIdentity, resource_generation) == 16);
const _: () = assert!(std::mem::offset_of!(PrimeMcIdentity, epoch) == 24);
const _: () = assert!(std::mem::offset_of!(PrimeMcIdentity, batch) == 32);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeMcRange {
    pub offset: u64,
    pub count: u64,
}
impl Default for PrimeMcRange {
    fn default() -> Self {
        Self {
            offset: 0,
            count: 0,
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeMcRange>() == 16);
const _: () = assert!(std::mem::align_of::<PrimeMcRange>() == 8);
const _: () = assert!(std::mem::offset_of!(PrimeMcRange, offset) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeMcRange, count) == 8);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeMcEvent {
    pub kind: u32,
    pub x: i32,
    pub y: i32,
    pub z: i32,
}
impl Default for PrimeMcEvent {
    fn default() -> Self {
        Self {
            kind: 0,
            x: 0,
            y: 0,
            z: 0,
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeMcEvent>() == 16);
const _: () = assert!(std::mem::align_of::<PrimeMcEvent>() == 4);
const _: () = assert!(std::mem::offset_of!(PrimeMcEvent, kind) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeMcEvent, x) == 4);
const _: () = assert!(std::mem::offset_of!(PrimeMcEvent, y) == 8);
const _: () = assert!(std::mem::offset_of!(PrimeMcEvent, z) == 12);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeMcPlan {
    pub identity: PrimeMcIdentity,
    pub position: [f64; 2],
    pub radius: i32,
    pub min_y: i32,
    pub max_y: i32,
    pub source: [i32; 4],
    pub reserved: u32,
    pub tick: u64,
    pub events: *const PrimeMcEvent,
    pub event_count: u64,
}
impl Default for PrimeMcPlan {
    fn default() -> Self {
        Self {
            identity: PrimeMcIdentity::default(),
            position: [0.0; 2],
            radius: 0,
            min_y: 0,
            max_y: 0,
            source: [0; 4],
            reserved: 0,
            tick: 0,
            events: std::ptr::null(),
            event_count: 0,
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeMcPlan>() == 112);
const _: () = assert!(std::mem::align_of::<PrimeMcPlan>() == 8);
const _: () = assert!(std::mem::offset_of!(PrimeMcPlan, identity) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeMcPlan, position) == 40);
const _: () = assert!(std::mem::offset_of!(PrimeMcPlan, radius) == 56);
const _: () = assert!(std::mem::offset_of!(PrimeMcPlan, min_y) == 60);
const _: () = assert!(std::mem::offset_of!(PrimeMcPlan, max_y) == 64);
const _: () = assert!(std::mem::offset_of!(PrimeMcPlan, source) == 68);
const _: () = assert!(std::mem::offset_of!(PrimeMcPlan, reserved) == 84);
const _: () = assert!(std::mem::offset_of!(PrimeMcPlan, tick) == 88);
const _: () = assert!(std::mem::offset_of!(PrimeMcPlan, events) == 96);
const _: () = assert!(std::mem::offset_of!(PrimeMcPlan, event_count) == 104);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeMcPlacement {
    pub offset: u32,
    pub horizontal: f32,
    pub vertical: f32,
    pub seed: u32,
}
impl Default for PrimeMcPlacement {
    fn default() -> Self {
        Self {
            offset: 0,
            horizontal: 0.0,
            vertical: 0.0,
            seed: 0,
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeMcPlacement>() == 16);
const _: () = assert!(std::mem::align_of::<PrimeMcPlacement>() == 4);
const _: () = assert!(std::mem::offset_of!(PrimeMcPlacement, offset) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeMcPlacement, horizontal) == 4);
const _: () = assert!(std::mem::offset_of!(PrimeMcPlacement, vertical) == 8);
const _: () = assert!(std::mem::offset_of!(PrimeMcPlacement, seed) == 12);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeMcState {
    pub id: u32,
    pub flags: u32,
    pub model: u32,
    pub faces: [u32; 6],
    pub support: u32,
    pub fluid_level: u32,
    pub fluid_falling: u32,
    pub fluid_material: u32,
    pub emission: u32,
    pub placement: PrimeMcPlacement,
    pub name: PrimeMcRange,
    pub fluid_name: PrimeMcRange,
}
impl Default for PrimeMcState {
    fn default() -> Self {
        Self {
            id: 0,
            flags: 0,
            model: 0,
            faces: [0; 6],
            support: 0,
            fluid_level: 0,
            fluid_falling: 0,
            fluid_material: 0,
            emission: 0,
            placement: PrimeMcPlacement::default(),
            name: PrimeMcRange::default(),
            fluid_name: PrimeMcRange::default(),
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeMcState>() == 104);
const _: () = assert!(std::mem::align_of::<PrimeMcState>() == 8);
const _: () = assert!(std::mem::offset_of!(PrimeMcState, id) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeMcState, flags) == 4);
const _: () = assert!(std::mem::offset_of!(PrimeMcState, model) == 8);
const _: () = assert!(std::mem::offset_of!(PrimeMcState, faces) == 12);
const _: () = assert!(std::mem::offset_of!(PrimeMcState, support) == 36);
const _: () = assert!(std::mem::offset_of!(PrimeMcState, fluid_level) == 40);
const _: () = assert!(std::mem::offset_of!(PrimeMcState, fluid_falling) == 44);
const _: () = assert!(std::mem::offset_of!(PrimeMcState, fluid_material) == 48);
const _: () = assert!(std::mem::offset_of!(PrimeMcState, emission) == 52);
const _: () = assert!(std::mem::offset_of!(PrimeMcState, placement) == 56);
const _: () = assert!(std::mem::offset_of!(PrimeMcState, name) == 72);
const _: () = assert!(std::mem::offset_of!(PrimeMcState, fluid_name) == 88);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeMcQuad {
    pub face: u32,
    pub tint: i32,
    pub layer: u32,
    pub sprite: u32,
    pub emission: u32,
    pub reserved: u32,
    pub positions: [f32; 12],
    pub uv_pairs: [u64; 4],
}
impl Default for PrimeMcQuad {
    fn default() -> Self {
        Self {
            face: 0,
            tint: 0,
            layer: 0,
            sprite: 0,
            emission: 0,
            reserved: 0,
            positions: [0.0; 12],
            uv_pairs: [0; 4],
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeMcQuad>() == 104);
const _: () = assert!(std::mem::align_of::<PrimeMcQuad>() == 8);
const _: () = assert!(std::mem::offset_of!(PrimeMcQuad, face) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeMcQuad, tint) == 4);
const _: () = assert!(std::mem::offset_of!(PrimeMcQuad, layer) == 8);
const _: () = assert!(std::mem::offset_of!(PrimeMcQuad, sprite) == 12);
const _: () = assert!(std::mem::offset_of!(PrimeMcQuad, emission) == 16);
const _: () = assert!(std::mem::offset_of!(PrimeMcQuad, reserved) == 20);
const _: () = assert!(std::mem::offset_of!(PrimeMcQuad, positions) == 24);
const _: () = assert!(std::mem::offset_of!(PrimeMcQuad, uv_pairs) == 72);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeMcModelChild {
    pub weight: u32,
    pub model: u32,
}
impl Default for PrimeMcModelChild {
    fn default() -> Self {
        Self {
            weight: 0,
            model: 0,
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeMcModelChild>() == 8);
const _: () = assert!(std::mem::align_of::<PrimeMcModelChild>() == 4);
const _: () = assert!(std::mem::offset_of!(PrimeMcModelChild, weight) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeMcModelChild, model) == 4);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeMcModel {
    pub id: u32,
    pub kind: u32,
    pub alias: u32,
    pub reserved: u32,
    pub quads: PrimeMcRange,
    pub children: PrimeMcRange,
}
impl Default for PrimeMcModel {
    fn default() -> Self {
        Self {
            id: 0,
            kind: 0,
            alias: 0,
            reserved: 0,
            quads: PrimeMcRange::default(),
            children: PrimeMcRange::default(),
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeMcModel>() == 48);
const _: () = assert!(std::mem::align_of::<PrimeMcModel>() == 8);
const _: () = assert!(std::mem::offset_of!(PrimeMcModel, id) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeMcModel, kind) == 4);
const _: () = assert!(std::mem::offset_of!(PrimeMcModel, alias) == 8);
const _: () = assert!(std::mem::offset_of!(PrimeMcModel, reserved) == 12);
const _: () = assert!(std::mem::offset_of!(PrimeMcModel, quads) == 16);
const _: () = assert!(std::mem::offset_of!(PrimeMcModel, children) == 32);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeMcFace {
    pub id: u32,
    pub reserved: u32,
    pub u: PrimeMcRange,
    pub v: PrimeMcRange,
    pub words: PrimeMcRange,
}
impl Default for PrimeMcFace {
    fn default() -> Self {
        Self {
            id: 0,
            reserved: 0,
            u: PrimeMcRange::default(),
            v: PrimeMcRange::default(),
            words: PrimeMcRange::default(),
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeMcFace>() == 56);
const _: () = assert!(std::mem::align_of::<PrimeMcFace>() == 8);
const _: () = assert!(std::mem::offset_of!(PrimeMcFace, id) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeMcFace, reserved) == 4);
const _: () = assert!(std::mem::offset_of!(PrimeMcFace, u) == 8);
const _: () = assert!(std::mem::offset_of!(PrimeMcFace, v) == 24);
const _: () = assert!(std::mem::offset_of!(PrimeMcFace, words) == 40);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeMcFluid {
    pub id: u32,
    pub layer: u32,
    pub flags: u32,
    pub identities: [u32; 3],
    pub bounds: [f32; 12],
}
impl Default for PrimeMcFluid {
    fn default() -> Self {
        Self {
            id: 0,
            layer: 0,
            flags: 0,
            identities: [0; 3],
            bounds: [0.0; 12],
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeMcFluid>() == 72);
const _: () = assert!(std::mem::align_of::<PrimeMcFluid>() == 4);
const _: () = assert!(std::mem::offset_of!(PrimeMcFluid, id) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeMcFluid, layer) == 4);
const _: () = assert!(std::mem::offset_of!(PrimeMcFluid, flags) == 8);
const _: () = assert!(std::mem::offset_of!(PrimeMcFluid, identities) == 12);
const _: () = assert!(std::mem::offset_of!(PrimeMcFluid, bounds) == 24);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeMcImage {
    pub width: u32,
    pub height: u32,
    pub pixels: PrimeMcRange,
}
impl Default for PrimeMcImage {
    fn default() -> Self {
        Self {
            width: 0,
            height: 0,
            pixels: PrimeMcRange::default(),
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeMcImage>() == 24);
const _: () = assert!(std::mem::align_of::<PrimeMcImage>() == 8);
const _: () = assert!(std::mem::offset_of!(PrimeMcImage, width) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeMcImage, height) == 4);
const _: () = assert!(std::mem::offset_of!(PrimeMcImage, pixels) == 8);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeMcAnimationFrame {
    pub frame: u32,
    pub duration: u32,
}
impl Default for PrimeMcAnimationFrame {
    fn default() -> Self {
        Self {
            frame: 0,
            duration: 0,
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeMcAnimationFrame>() == 8);
const _: () = assert!(std::mem::align_of::<PrimeMcAnimationFrame>() == 4);
const _: () = assert!(std::mem::offset_of!(PrimeMcAnimationFrame, frame) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeMcAnimationFrame, duration) == 4);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeMcSprite {
    pub id: u32,
    pub interpolate: u32,
    pub bounds: [f32; 4],
    pub extent: [u32; 2],
    pub name: PrimeMcRange,
    pub images: PrimeMcRange,
    pub frames: PrimeMcRange,
    pub normal_image: u32,
    pub specular_image: u32,
}
impl Default for PrimeMcSprite {
    fn default() -> Self {
        Self {
            id: 0,
            interpolate: 0,
            bounds: [0.0; 4],
            extent: [0; 2],
            name: PrimeMcRange::default(),
            images: PrimeMcRange::default(),
            frames: PrimeMcRange::default(),
            normal_image: 0,
            specular_image: 0,
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeMcSprite>() == 88);
const _: () = assert!(std::mem::align_of::<PrimeMcSprite>() == 8);
const _: () = assert!(std::mem::offset_of!(PrimeMcSprite, id) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeMcSprite, interpolate) == 4);
const _: () = assert!(std::mem::offset_of!(PrimeMcSprite, bounds) == 8);
const _: () = assert!(std::mem::offset_of!(PrimeMcSprite, extent) == 24);
const _: () = assert!(std::mem::offset_of!(PrimeMcSprite, name) == 32);
const _: () = assert!(std::mem::offset_of!(PrimeMcSprite, images) == 48);
const _: () = assert!(std::mem::offset_of!(PrimeMcSprite, frames) == 64);
const _: () = assert!(std::mem::offset_of!(PrimeMcSprite, normal_image) == 80);
const _: () = assert!(std::mem::offset_of!(PrimeMcSprite, specular_image) == 84);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeMcResourceBatch {
    pub identity: PrimeMcIdentity,
    pub flags: u32,
    pub reserved: u32,
    pub tick: u64,
    pub atlas: PrimeMcImage,
    pub states: *const PrimeMcState,
    pub state_count: u64,
    pub models: *const PrimeMcModel,
    pub model_count: u64,
    pub quads: *const PrimeMcQuad,
    pub quad_count: u64,
    pub children: *const PrimeMcModelChild,
    pub child_count: u64,
    pub faces: *const PrimeMcFace,
    pub face_count: u64,
    pub fluids: *const PrimeMcFluid,
    pub fluid_count: u64,
    pub sprites: *const PrimeMcSprite,
    pub sprite_count: u64,
    pub images: *const PrimeMcImage,
    pub image_count: u64,
    pub frames: *const PrimeMcAnimationFrame,
    pub frame_count: u64,
    pub coordinates: *const f64,
    pub coordinate_count: u64,
    pub words: *const u64,
    pub word_count: u64,
    pub bytes: *const u8,
    pub byte_count: u64,
}
impl Default for PrimeMcResourceBatch {
    fn default() -> Self {
        Self {
            identity: PrimeMcIdentity::default(),
            flags: 0,
            reserved: 0,
            tick: 0,
            atlas: PrimeMcImage::default(),
            states: std::ptr::null(),
            state_count: 0,
            models: std::ptr::null(),
            model_count: 0,
            quads: std::ptr::null(),
            quad_count: 0,
            children: std::ptr::null(),
            child_count: 0,
            faces: std::ptr::null(),
            face_count: 0,
            fluids: std::ptr::null(),
            fluid_count: 0,
            sprites: std::ptr::null(),
            sprite_count: 0,
            images: std::ptr::null(),
            image_count: 0,
            frames: std::ptr::null(),
            frame_count: 0,
            coordinates: std::ptr::null(),
            coordinate_count: 0,
            words: std::ptr::null(),
            word_count: 0,
            bytes: std::ptr::null(),
            byte_count: 0,
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeMcResourceBatch>() == 272);
const _: () = assert!(std::mem::align_of::<PrimeMcResourceBatch>() == 8);
const _: () = assert!(std::mem::offset_of!(PrimeMcResourceBatch, identity) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeMcResourceBatch, flags) == 40);
const _: () = assert!(std::mem::offset_of!(PrimeMcResourceBatch, reserved) == 44);
const _: () = assert!(std::mem::offset_of!(PrimeMcResourceBatch, tick) == 48);
const _: () = assert!(std::mem::offset_of!(PrimeMcResourceBatch, atlas) == 56);
const _: () = assert!(std::mem::offset_of!(PrimeMcResourceBatch, states) == 80);
const _: () = assert!(std::mem::offset_of!(PrimeMcResourceBatch, state_count) == 88);
const _: () = assert!(std::mem::offset_of!(PrimeMcResourceBatch, models) == 96);
const _: () = assert!(std::mem::offset_of!(PrimeMcResourceBatch, model_count) == 104);
const _: () = assert!(std::mem::offset_of!(PrimeMcResourceBatch, quads) == 112);
const _: () = assert!(std::mem::offset_of!(PrimeMcResourceBatch, quad_count) == 120);
const _: () = assert!(std::mem::offset_of!(PrimeMcResourceBatch, children) == 128);
const _: () = assert!(std::mem::offset_of!(PrimeMcResourceBatch, child_count) == 136);
const _: () = assert!(std::mem::offset_of!(PrimeMcResourceBatch, faces) == 144);
const _: () = assert!(std::mem::offset_of!(PrimeMcResourceBatch, face_count) == 152);
const _: () = assert!(std::mem::offset_of!(PrimeMcResourceBatch, fluids) == 160);
const _: () = assert!(std::mem::offset_of!(PrimeMcResourceBatch, fluid_count) == 168);
const _: () = assert!(std::mem::offset_of!(PrimeMcResourceBatch, sprites) == 176);
const _: () = assert!(std::mem::offset_of!(PrimeMcResourceBatch, sprite_count) == 184);
const _: () = assert!(std::mem::offset_of!(PrimeMcResourceBatch, images) == 192);
const _: () = assert!(std::mem::offset_of!(PrimeMcResourceBatch, image_count) == 200);
const _: () = assert!(std::mem::offset_of!(PrimeMcResourceBatch, frames) == 208);
const _: () = assert!(std::mem::offset_of!(PrimeMcResourceBatch, frame_count) == 216);
const _: () = assert!(std::mem::offset_of!(PrimeMcResourceBatch, coordinates) == 224);
const _: () = assert!(std::mem::offset_of!(PrimeMcResourceBatch, coordinate_count) == 232);
const _: () = assert!(std::mem::offset_of!(PrimeMcResourceBatch, words) == 240);
const _: () = assert!(std::mem::offset_of!(PrimeMcResourceBatch, word_count) == 248);
const _: () = assert!(std::mem::offset_of!(PrimeMcResourceBatch, bytes) == 256);
const _: () = assert!(std::mem::offset_of!(PrimeMcResourceBatch, byte_count) == 264);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeMcSection {
    pub x: i32,
    pub y: i32,
    pub z: i32,
    pub present: u32,
    pub bits: u32,
    pub reserved: u32,
    pub palette: PrimeMcRange,
    pub storage: PrimeMcRange,
}
impl Default for PrimeMcSection {
    fn default() -> Self {
        Self {
            x: 0,
            y: 0,
            z: 0,
            present: 0,
            bits: 0,
            reserved: 0,
            palette: PrimeMcRange::default(),
            storage: PrimeMcRange::default(),
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeMcSection>() == 56);
const _: () = assert!(std::mem::align_of::<PrimeMcSection>() == 8);
const _: () = assert!(std::mem::offset_of!(PrimeMcSection, x) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeMcSection, y) == 4);
const _: () = assert!(std::mem::offset_of!(PrimeMcSection, z) == 8);
const _: () = assert!(std::mem::offset_of!(PrimeMcSection, present) == 12);
const _: () = assert!(std::mem::offset_of!(PrimeMcSection, bits) == 16);
const _: () = assert!(std::mem::offset_of!(PrimeMcSection, reserved) == 20);
const _: () = assert!(std::mem::offset_of!(PrimeMcSection, palette) == 24);
const _: () = assert!(std::mem::offset_of!(PrimeMcSection, storage) == 40);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeMcSectionBatch {
    pub identity: PrimeMcIdentity,
    pub sections: *const PrimeMcSection,
    pub section_count: u64,
    pub palette: *const u32,
    pub palette_count: u64,
    pub words: *const u64,
    pub word_count: u64,
}
impl Default for PrimeMcSectionBatch {
    fn default() -> Self {
        Self {
            identity: PrimeMcIdentity::default(),
            sections: std::ptr::null(),
            section_count: 0,
            palette: std::ptr::null(),
            palette_count: 0,
            words: std::ptr::null(),
            word_count: 0,
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeMcSectionBatch>() == 88);
const _: () = assert!(std::mem::align_of::<PrimeMcSectionBatch>() == 8);
const _: () = assert!(std::mem::offset_of!(PrimeMcSectionBatch, identity) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeMcSectionBatch, sections) == 40);
const _: () = assert!(std::mem::offset_of!(PrimeMcSectionBatch, section_count) == 48);
const _: () = assert!(std::mem::offset_of!(PrimeMcSectionBatch, palette) == 56);
const _: () = assert!(std::mem::offset_of!(PrimeMcSectionBatch, palette_count) == 64);
const _: () = assert!(std::mem::offset_of!(PrimeMcSectionBatch, words) == 72);
const _: () = assert!(std::mem::offset_of!(PrimeMcSectionBatch, word_count) == 80);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeMcSectionRequest {
    pub x: i32,
    pub y: i32,
    pub z: i32,
    pub active: u32,
}
impl Default for PrimeMcSectionRequest {
    fn default() -> Self {
        Self {
            x: 0,
            y: 0,
            z: 0,
            active: 0,
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeMcSectionRequest>() == 16);
const _: () = assert!(std::mem::align_of::<PrimeMcSectionRequest>() == 4);
const _: () = assert!(std::mem::offset_of!(PrimeMcSectionRequest, x) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeMcSectionRequest, y) == 4);
const _: () = assert!(std::mem::offset_of!(PrimeMcSectionRequest, z) == 8);
const _: () = assert!(std::mem::offset_of!(PrimeMcSectionRequest, active) == 12);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeMcColumnRequest {
    pub x: i32,
    pub z: i32,
    pub active: u32,
}
impl Default for PrimeMcColumnRequest {
    fn default() -> Self {
        Self {
            x: 0,
            z: 0,
            active: 0,
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeMcColumnRequest>() == 12);
const _: () = assert!(std::mem::align_of::<PrimeMcColumnRequest>() == 4);
const _: () = assert!(std::mem::offset_of!(PrimeMcColumnRequest, x) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeMcColumnRequest, z) == 4);
const _: () = assert!(std::mem::offset_of!(PrimeMcColumnRequest, active) == 8);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeMcColorRequest {
    pub x: i32,
    pub y: i32,
    pub z: i32,
    pub state: u32,
    pub slot: i32,
}
impl Default for PrimeMcColorRequest {
    fn default() -> Self {
        Self {
            x: 0,
            y: 0,
            z: 0,
            state: 0,
            slot: 0,
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeMcColorRequest>() == 20);
const _: () = assert!(std::mem::align_of::<PrimeMcColorRequest>() == 4);
const _: () = assert!(std::mem::offset_of!(PrimeMcColorRequest, x) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeMcColorRequest, y) == 4);
const _: () = assert!(std::mem::offset_of!(PrimeMcColorRequest, z) == 8);
const _: () = assert!(std::mem::offset_of!(PrimeMcColorRequest, state) == 12);
const _: () = assert!(std::mem::offset_of!(PrimeMcColorRequest, slot) == 16);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeMcBiomeRequest {
    pub x: i32,
    pub y: i32,
    pub z: i32,
    pub reserved: u32,
    pub mask: u64,
}
impl Default for PrimeMcBiomeRequest {
    fn default() -> Self {
        Self {
            x: 0,
            y: 0,
            z: 0,
            reserved: 0,
            mask: 0,
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeMcBiomeRequest>() == 24);
const _: () = assert!(std::mem::align_of::<PrimeMcBiomeRequest>() == 8);
const _: () = assert!(std::mem::offset_of!(PrimeMcBiomeRequest, x) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeMcBiomeRequest, y) == 4);
const _: () = assert!(std::mem::offset_of!(PrimeMcBiomeRequest, z) == 8);
const _: () = assert!(std::mem::offset_of!(PrimeMcBiomeRequest, reserved) == 12);
const _: () = assert!(std::mem::offset_of!(PrimeMcBiomeRequest, mask) == 16);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeMcRequests {
    pub identity: PrimeMcIdentity,
    pub phase: u32,
    pub reserved: u32,
    pub active_sections: u64,
    pub sections: *const PrimeMcSectionRequest,
    pub section_count: u64,
    pub columns: *const PrimeMcColumnRequest,
    pub column_count: u64,
    pub colors: *const PrimeMcColorRequest,
    pub color_count: u64,
    pub biomes: *const PrimeMcBiomeRequest,
    pub biome_count: u64,
}
impl Default for PrimeMcRequests {
    fn default() -> Self {
        Self {
            identity: PrimeMcIdentity::default(),
            phase: 0,
            reserved: 0,
            active_sections: 0,
            sections: std::ptr::null(),
            section_count: 0,
            columns: std::ptr::null(),
            column_count: 0,
            colors: std::ptr::null(),
            color_count: 0,
            biomes: std::ptr::null(),
            biome_count: 0,
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeMcRequests>() == 120);
const _: () = assert!(std::mem::align_of::<PrimeMcRequests>() == 8);
const _: () = assert!(std::mem::offset_of!(PrimeMcRequests, identity) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeMcRequests, phase) == 40);
const _: () = assert!(std::mem::offset_of!(PrimeMcRequests, reserved) == 44);
const _: () = assert!(std::mem::offset_of!(PrimeMcRequests, active_sections) == 48);
const _: () = assert!(std::mem::offset_of!(PrimeMcRequests, sections) == 56);
const _: () = assert!(std::mem::offset_of!(PrimeMcRequests, section_count) == 64);
const _: () = assert!(std::mem::offset_of!(PrimeMcRequests, columns) == 72);
const _: () = assert!(std::mem::offset_of!(PrimeMcRequests, column_count) == 80);
const _: () = assert!(std::mem::offset_of!(PrimeMcRequests, colors) == 88);
const _: () = assert!(std::mem::offset_of!(PrimeMcRequests, color_count) == 96);
const _: () = assert!(std::mem::offset_of!(PrimeMcRequests, biomes) == 104);
const _: () = assert!(std::mem::offset_of!(PrimeMcRequests, biome_count) == 112);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeMcColorRecipe {
    pub kind: u32,
    pub value: u32,
}
impl Default for PrimeMcColorRecipe {
    fn default() -> Self {
        Self { kind: 0, value: 0 }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeMcColorRecipe>() == 8);
const _: () = assert!(std::mem::align_of::<PrimeMcColorRecipe>() == 4);
const _: () = assert!(std::mem::offset_of!(PrimeMcColorRecipe, kind) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeMcColorRecipe, value) == 4);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeMcBiomeDefinitions {
    pub seed: u64,
    pub permutation: [u32; 256],
    pub offset: [f64; 2],
    pub input_scale: f64,
    pub value_scale: f64,
    pub grass: PrimeMcRange,
    pub foliage: PrimeMcRange,
    pub dry_foliage: PrimeMcRange,
}
impl Default for PrimeMcBiomeDefinitions {
    fn default() -> Self {
        Self {
            seed: 0,
            permutation: [0; 256],
            offset: [0.0; 2],
            input_scale: 0.0,
            value_scale: 0.0,
            grass: PrimeMcRange::default(),
            foliage: PrimeMcRange::default(),
            dry_foliage: PrimeMcRange::default(),
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeMcBiomeDefinitions>() == 1112);
const _: () = assert!(std::mem::align_of::<PrimeMcBiomeDefinitions>() == 8);
const _: () = assert!(std::mem::offset_of!(PrimeMcBiomeDefinitions, seed) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeMcBiomeDefinitions, permutation) == 8);
const _: () = assert!(std::mem::offset_of!(PrimeMcBiomeDefinitions, offset) == 1032);
const _: () = assert!(std::mem::offset_of!(PrimeMcBiomeDefinitions, input_scale) == 1048);
const _: () = assert!(std::mem::offset_of!(PrimeMcBiomeDefinitions, value_scale) == 1056);
const _: () = assert!(std::mem::offset_of!(PrimeMcBiomeDefinitions, grass) == 1064);
const _: () = assert!(std::mem::offset_of!(PrimeMcBiomeDefinitions, foliage) == 1080);
const _: () = assert!(std::mem::offset_of!(PrimeMcBiomeDefinitions, dry_foliage) == 1096);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeMcColorBatch {
    pub identity: PrimeMcIdentity,
    pub radius: i32,
    pub reserved: u32,
    pub recipes: *const PrimeMcColorRecipe,
    pub recipe_count: u64,
    pub definitions: *const PrimeMcBiomeDefinitions,
    pub definition_count: u64,
    pub colormaps: *const u32,
    pub colormap_count: u64,
}
impl Default for PrimeMcColorBatch {
    fn default() -> Self {
        Self {
            identity: PrimeMcIdentity::default(),
            radius: 0,
            reserved: 0,
            recipes: std::ptr::null(),
            recipe_count: 0,
            definitions: std::ptr::null(),
            definition_count: 0,
            colormaps: std::ptr::null(),
            colormap_count: 0,
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeMcColorBatch>() == 96);
const _: () = assert!(std::mem::align_of::<PrimeMcColorBatch>() == 8);
const _: () = assert!(std::mem::offset_of!(PrimeMcColorBatch, identity) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeMcColorBatch, radius) == 40);
const _: () = assert!(std::mem::offset_of!(PrimeMcColorBatch, reserved) == 44);
const _: () = assert!(std::mem::offset_of!(PrimeMcColorBatch, recipes) == 48);
const _: () = assert!(std::mem::offset_of!(PrimeMcColorBatch, recipe_count) == 56);
const _: () = assert!(std::mem::offset_of!(PrimeMcColorBatch, definitions) == 64);
const _: () = assert!(std::mem::offset_of!(PrimeMcColorBatch, definition_count) == 72);
const _: () = assert!(std::mem::offset_of!(PrimeMcColorBatch, colormaps) == 80);
const _: () = assert!(std::mem::offset_of!(PrimeMcColorBatch, colormap_count) == 88);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeMcBiome {
    pub temperature: f32,
    pub downfall: f32,
    pub water: u32,
    pub overrides: [u32; 3],
    pub flags: u32,
    pub modifier: u32,
}
impl Default for PrimeMcBiome {
    fn default() -> Self {
        Self {
            temperature: 0.0,
            downfall: 0.0,
            water: 0,
            overrides: [0; 3],
            flags: 0,
            modifier: 0,
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeMcBiome>() == 32);
const _: () = assert!(std::mem::align_of::<PrimeMcBiome>() == 4);
const _: () = assert!(std::mem::offset_of!(PrimeMcBiome, temperature) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeMcBiome, downfall) == 4);
const _: () = assert!(std::mem::offset_of!(PrimeMcBiome, water) == 8);
const _: () = assert!(std::mem::offset_of!(PrimeMcBiome, overrides) == 12);
const _: () = assert!(std::mem::offset_of!(PrimeMcBiome, flags) == 24);
const _: () = assert!(std::mem::offset_of!(PrimeMcBiome, modifier) == 28);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct PrimeMcBiomeBatch {
    pub identity: PrimeMcIdentity,
    pub biomes: *const PrimeMcBiome,
    pub biome_count: u64,
    pub indices: *const u32,
    pub index_count: u64,
}
impl Default for PrimeMcBiomeBatch {
    fn default() -> Self {
        Self {
            identity: PrimeMcIdentity::default(),
            biomes: std::ptr::null(),
            biome_count: 0,
            indices: std::ptr::null(),
            index_count: 0,
        }
    }
}
const _: () = assert!(std::mem::size_of::<PrimeMcBiomeBatch>() == 72);
const _: () = assert!(std::mem::align_of::<PrimeMcBiomeBatch>() == 8);
const _: () = assert!(std::mem::offset_of!(PrimeMcBiomeBatch, identity) == 0);
const _: () = assert!(std::mem::offset_of!(PrimeMcBiomeBatch, biomes) == 40);
const _: () = assert!(std::mem::offset_of!(PrimeMcBiomeBatch, biome_count) == 48);
const _: () = assert!(std::mem::offset_of!(PrimeMcBiomeBatch, indices) == 56);
const _: () = assert!(std::mem::offset_of!(PrimeMcBiomeBatch, index_count) == 64);
pub type PrimeAbiVersionFn = unsafe extern "C" fn() -> u32;
pub type PrimeCreateFn = unsafe extern "C" fn(u32) -> u64;
pub type PrimeResetFn = unsafe extern "C" fn(u64, *const PrimeReset) -> i32;
pub type PrimeTexturesFn = unsafe extern "C" fn(u64, *const PrimeTextureBatch) -> i32;
pub type PrimeRetireTexturesFn = unsafe extern "C" fn(u64, *const PrimeTextureRetire) -> i32;
pub type PrimeDynamicFn = unsafe extern "C" fn(u64, *const PrimeDynamicBatch) -> i32;
pub type PrimeInstancesFn = unsafe extern "C" fn(u64, *const PrimeInstanceBatch) -> i32;
pub type PrimeAttachVulkanFn = unsafe extern "C" fn(u64, *const PrimeVulkanHost) -> i32;
pub type PrimeConfigureFn = unsafe extern "C" fn(u64, *const PrimeSettings) -> i32;
pub type PrimePrepareResourcesFn = unsafe extern "C" fn(u64, *const PrimePrepareResources) -> i32;
pub type PrimeRecordFn =
    unsafe extern "C" fn(u64, *const PrimeFrame, *const PrimeRecordTarget) -> i32;
pub type PrimeSubmissionAcceptedFn = unsafe extern "C" fn(u64, u64) -> i32;
pub type PrimeDisplayOutputFn = unsafe extern "C" fn(u64, *const PrimeDisplayOutput) -> i32;
pub type PrimePresentHdrFn = unsafe extern "C" fn(u64, *const PrimeHdrTarget) -> i32;
pub type PrimePrepareFrameGenerationFn =
    unsafe extern "C" fn(u64, *const PrimeHdrTarget, u32, u32) -> i32;
pub type PrimeHdrSurfaceCreateFn = unsafe extern "C" fn(*const PrimeVulkanHost) -> u64;
pub type PrimeHdrSurfaceRecordFn =
    unsafe extern "C" fn(u64, *const PrimeHdrTarget, *const PrimeDisplayOutput) -> i32;
pub type PrimeHdrSurfaceDestroyFn = unsafe extern "C" fn(u64) -> i32;
pub type PrimeRenderFn = unsafe extern "C" fn(u64, *const PrimeFrame, *mut u8, u64) -> i32;
pub type PrimeGpuTimeFn = unsafe extern "C" fn(u64) -> u64;
pub type PrimeCpuDiagnosticsFn = unsafe extern "C" fn(u64, *mut u8, u64) -> u64;
pub type PrimeDestroyFn = unsafe extern "C" fn(u64) -> i32;
pub type PrimeLastErrorFn = unsafe extern "C" fn(*mut u8, u64) -> u64;
pub type PrimeStreamlinePresentFn = unsafe extern "C" fn(u64, u64) -> i32;
pub type PrimeStreamlineBootstrapFn = unsafe extern "C" fn() -> i32;
pub type PrimeStreamlineFrameFn = unsafe extern "C" fn(u32, u32) -> i32;
pub type PrimeMcResourcesFn = unsafe extern "C" fn(u64, *const PrimeMcResourceBatch) -> i32;
pub type PrimeMcPlanFn = unsafe extern "C" fn(u64, *const PrimeMcPlan, *mut PrimeMcRequests) -> i32;
pub type PrimeMcSectionsFn =
    unsafe extern "C" fn(u64, *const PrimeMcSectionBatch, *mut PrimeMcRequests) -> i32;
pub type PrimeMcColorsFn =
    unsafe extern "C" fn(u64, *const PrimeMcColorBatch, *mut PrimeMcRequests) -> i32;
pub type PrimeMcBiomesFn =
    unsafe extern "C" fn(u64, *const PrimeMcBiomeBatch, *mut PrimeMcRequests) -> i32;
