[package]
license.workspace = true
name = "prime_scene"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Version-neutral source protocol, scene values and CPU scene translation"

[dependencies]
prime_abi.workspace = true
rayon.workspace = true
rectangle_decomposition = { path = "../rectangle-decomposition" }

[lints]
workspace = true
