// Generated by scripts/generate-abi.py; edit C headers, not this file.
// Compiled in the implementation module: every declared export must exist and match.
const _: prime_abi::PrimeMcResourcesFn = prime_mc_resources;
const _: prime_abi::PrimeMcPlanFn = prime_mc_plan;
const _: prime_abi::PrimeMcSectionsFn = prime_mc_sections;
const _: prime_abi::PrimeMcColorsFn = prime_mc_colors;
const _: prime_abi::PrimeMcBiomesFn = prime_mc_biomes;
