//! Renderer values contain no Minecraft objects, borrowed FFM memory or Vulkan handles.
use crate::geometry::MeshGeometry;
use crate::instances::InstanceContext;
use crate::spatial::{Cell, TerrainAvailability};
use std::{
    collections::{BTreeMap, BTreeSet},
    sync::Arc,
};

#[derive(Clone, Copy, Debug)]
pub struct Triangle {
    pub positions: [[f32; 3]; 3],
    /// Source encoded RGBA tint. Decode RGB only after texture × tint at the hit.
    pub colors: [[f32; 4]; 3],
    pub uvs: [[f32; 2]; 3],
    pub texture_id: u32,
    pub flags: u32,
}

#[derive(Clone, Debug)]
pub struct Texture {
    pub width: u32,
    pub height: u32,
    pub pixels: Arc<[u8]>,
    /// Optional pixel window in the shared backing image. Static sprite views share atlas
    /// storage; their direct GPU descriptor carries offset, extent and row stride.
    pub region: Option<[u32; 4]>,
    /// Sprite-only filtering/animation. Ordinary captured textures keep the direct base view.
    pub sampling: Option<Arc<TextureSampling>>,
    /// Canonical material planes. Source encodings are translated before publication.
    pub material: Option<Arc<TextureMaterial>>,
}
#[derive(Clone, Debug, Default)]
pub struct TextureMaterial {
    /// RG tangent direction, B source AO, A GGX distribution perceptual roughness.
    pub normal: Option<Texture>,
    /// Complement roughness, canonical Fresnel identity, tagged SSS/porosity, emission.
    pub specular: Option<Texture>,
    /// Per-texel presence bits, or identities when `atlas_lookup` is set.
    pub coverage: Option<Texture>,
    /// Any source alpha below 255 authorizes replacing ordinal host emission.
    pub authored_emission: bool,
    /// Coverage texels store source texture identities, translated to GPU descriptor indices.
    pub atlas_lookup: bool,
    /// Normalized backing-atlas bounds used when resolving a material sprite from atlas UVs.
    pub bounds: Option<[f32; 4]>,
}
#[derive(Clone, Debug)]
pub struct TextureLevel {
    pub width: u32,
    pub height: u32,
    pub pixels: Arc<[u8]>,
    pub region: [u32; 4],
    pub next: [u32; 2],
}
#[derive(Clone, Debug)]
pub struct TextureSampling {
    /// Lower source mip images; never regenerated by the renderer.
    pub levels: Vec<TextureLevel>,
    pub next: [u32; 2],
    /// Animation interpolates encoded RGBA and quantizes to the source UNORM8 atlas.
    pub blend: f32,
    /// Complete immutable set of possible base-image window offsets, independent of the
    /// current frame and interpolation. Empty means no complete animation-frame proof;
    /// ordinary static views also keep this empty. Does not change actual texel sampling.
    pub coverage_frames: Arc<[[u32; 2]]>,
}
impl Texture {
    fn color_backings(&self) -> impl Iterator<Item = &Arc<[u8]>> {
        std::iter::once(&self.pixels).chain(
            self.sampling
                .iter()
                .flat_map(|s| s.levels.iter().map(|m| &m.pixels)),
        )
    }
    pub fn backings(&self) -> impl Iterator<Item = &Arc<[u8]>> {
        self.color_backings()
            .chain(self.material.iter().flat_map(|m| {
                m.normal
                    .iter()
                    .chain(&m.specular)
                    .chain(&m.coverage)
                    .flat_map(Self::color_backings)
            }))
    }
    /// Same ordered immutable pixel allocations, independent of view/material metadata.
    /// A false result may still contain the same unique allocations in a different order.
    pub fn same_backings(&self, other: &Self) -> bool {
        let mut a = self.backings();
        let mut b = other.backings();
        loop {
            match (a.next(), b.next()) {
                (Some(a), Some(b)) => {
                    if !Arc::ptr_eq(a, b) {
                        return false;
                    }
                }
                (None, None) => return true,
                _ => return false,
            }
        }
    }
    pub fn same(&self, other: &Self) -> bool {
        self.width == other.width
            && self.height == other.height
            && self.region == other.region
            && Arc::ptr_eq(&self.pixels, &other.pixels)
            && match (&self.material, &other.material) {
                (None, None) => true,
                (Some(a), Some(b)) => {
                    Arc::ptr_eq(a, b) || {
                        let same = |a: &Option<Texture>, b: &Option<Texture>| match (a, b) {
                            (None, None) => true,
                            (Some(a), Some(b)) => a.same(b),
                            _ => false,
                        };
                        a.authored_emission == b.authored_emission
                            && a.atlas_lookup == b.atlas_lookup
                            && a.bounds == b.bounds
                            && same(&a.normal, &b.normal)
                            && same(&a.specular, &b.specular)
                            && same(&a.coverage, &b.coverage)
                    }
                }
                _ => false,
            }
            && match (&self.sampling, &other.sampling) {
                (None, None) => true,
                (Some(a), Some(b)) => {
                    Arc::ptr_eq(a, b)
                        || a.next == b.next
                            && a.blend == b.blend
                            && (Arc::ptr_eq(&a.coverage_frames, &b.coverage_frames)
                                || a.coverage_frames == b.coverage_frames)
                            && a.levels.len() == b.levels.len()
                            && a.levels.iter().zip(&b.levels).all(|(a, b)| {
                                a.width == b.width
                                    && a.height == b.height
                                    && a.region == b.region
                                    && a.next == b.next
                                    && Arc::ptr_eq(&a.pixels, &b.pixels)
                            })
                }
                _ => false,
            }
    }
    pub fn validate(&self) -> Result<(), String> {
        fn image(width: u32, height: u32, pixels: &[u8], region: [u32; 4], next: [u32; 2]) -> bool {
            width > 0
                && height > 0
                && width <= 16384
                && height <= 16384
                && u64::from(width) * u64::from(height) * 4 == pixels.len() as u64
                && region[2] > 0
                && region[3] > 0
                && [region[..2].try_into().unwrap(), next]
                    .into_iter()
                    .all(|p: [u32; 2]| {
                        u64::from(p[0]) + u64::from(region[2]) <= u64::from(width)
                            && u64::from(p[1]) + u64::from(region[3]) <= u64::from(height)
                    })
        }
        let r = self.region.unwrap_or([0, 0, self.width, self.height]);
        if !image(
            self.width,
            self.height,
            &self.pixels,
            r,
            self.sampling.as_ref().map_or([r[0], r[1]], |s| s.next),
        ) {
            return Err("invalid texture image/window".into());
        }
        if let Some(s) = &self.sampling {
            if self.region.is_none()
                || !s.blend.is_finite()
                || !(0.0..1.0).contains(&s.blend)
                || s.levels.len() > 14
            {
                return Err("invalid sprite sampling".into());
            }
            if !s.coverage_frames.is_empty() {
                let mut current = false;
                let mut next = false;
                for &p in s.coverage_frames.iter() {
                    if u64::from(p[0]) + u64::from(r[2]) > u64::from(self.width)
                        || u64::from(p[1]) + u64::from(r[3]) > u64::from(self.height)
                    {
                        return Err("invalid complete texture frame window".into());
                    }
                    current |= p == [r[0], r[1]];
                    next |= p == s.next;
                }
                if !current || !next {
                    return Err("sprite frame missing from complete texture frame windows".into());
                }
            }
            let mut extent = [r[2], r[3]];
            for m in &s.levels {
                extent = extent.map(|v| (v / 2).max(1));
                if m.region[2..] != extent || !image(m.width, m.height, &m.pixels, m.region, m.next)
                {
                    return Err("invalid sprite mip".into());
                }
            }
        }
        if let Some(material) = &self.material {
            if material.authored_emission && material.specular.is_none()
                || material.atlas_lookup && material.coverage.is_none()
                || material.bounds.is_some_and(|b| {
                    b.iter().any(|v| !v.is_finite() || !(0.0..=1.0).contains(v))
                        || b[0] >= b[2]
                        || b[1] >= b[3]
                })
            {
                return Err("invalid canonical material controls".into());
            }
            for plane in material
                .normal
                .iter()
                .chain(&material.specular)
                .chain(&material.coverage)
            {
                if plane.material.is_some()
                    || plane
                        .region
                        .map(|r| [r[2], r[3]])
                        .unwrap_or([plane.width, plane.height])
                        != [r[2], r[3]]
                {
                    return Err("invalid material plane extent or nesting".into());
                }
                plane.validate()?;
            }
        }
        Ok(())
    }
}

#[cfg(test)]
mod texture_tests {
    use super::*;

    fn plane() -> Texture {
        Texture {
            width: 4,
            height: 4,
            pixels: vec![255; 64].into(),
            region: Some([0, 0, 2, 2]),
            sampling: Some(Arc::new(TextureSampling {
                levels: vec![TextureLevel {
                    width: 2,
                    height: 2,
                    pixels: vec![255; 16].into(),
                    region: [0, 0, 1, 1],
                    next: [1, 1],
                }],
                next: [2, 2],
                blend: 0.25,
                coverage_frames: Arc::from([]),
            })),
            material: None,
        }
    }

    fn texture() -> Texture {
        let mut texture = plane();
        texture.material = Some(Arc::new(TextureMaterial {
            normal: Some(plane()),
            specular: Some(plane()),
            coverage: Some(plane()),
            ..Default::default()
        }));
        texture
    }

    #[test]
    fn backing_identity_ignores_changed_view_and_material_metadata() {
        let old = texture();
        let mut new = old.clone();
        new.region = Some([2, 0, 2, 2]);
        let sampling = Arc::make_mut(new.sampling.as_mut().unwrap());
        sampling.next = [0, 2];
        sampling.blend = 0.75;
        sampling.levels[0].region = [1, 0, 1, 1];
        sampling.levels[0].next = [0, 1];
        let material = Arc::make_mut(new.material.as_mut().unwrap());
        material.authored_emission = true;
        material.atlas_lookup = true;
        material.bounds = Some([0.25, 0.25, 0.75, 0.75]);
        old.validate().unwrap();
        new.validate().unwrap();
        assert!(!old.same(&new));
        assert!(old.same_backings(&new));
    }

    #[test]
    fn backing_identity_checks_all_planes_mips_order_and_duplicates() {
        let old = texture();
        let mut new = old.clone();
        // Equal bytes in a new allocation are a new pixel owner.
        new.pixels = old.pixels.to_vec().into();
        assert!(!old.same_backings(&new));
        for plane_index in 0..4 {
            let mut new = old.clone();
            let plane = if plane_index == 0 {
                &mut new
            } else {
                let material = Arc::make_mut(new.material.as_mut().unwrap());
                match plane_index {
                    1 => material.normal.as_mut().unwrap(),
                    2 => material.specular.as_mut().unwrap(),
                    _ => material.coverage.as_mut().unwrap(),
                }
            };
            let sampling = Arc::make_mut(plane.sampling.as_mut().unwrap());
            sampling.levels[0].pixels = sampling.levels[0].pixels.to_vec().into();
            assert!(!old.same_backings(&new));
        }
        let mut reordered = old.clone();
        let material = Arc::make_mut(reordered.material.as_mut().unwrap());
        std::mem::swap(&mut material.normal, &mut material.specular);
        assert!(!old.same_backings(&reordered));
        let mut duplicate = old.clone();
        let material = Arc::make_mut(duplicate.material.as_mut().unwrap());
        material.coverage = material.normal.clone();
        assert!(duplicate.same_backings(&duplicate.clone()));
        let mut fewer = duplicate.clone();
        Arc::make_mut(fewer.material.as_mut().unwrap()).coverage = None;
        assert!(!duplicate.same_backings(&fewer));
    }

    #[test]
    fn backing_identity_rejects_a_matching_prefix_in_either_direction() {
        let long = plane();
        let mut short = long.clone();
        short.sampling = None;
        long.validate().unwrap();
        short.validate().unwrap();
        assert_eq!(short.backings().count(), 1);
        assert_eq!(long.backings().count(), 2);
        assert!(short.same_backings(&short.clone()));
        assert!(!short.same_backings(&long));
        assert!(!long.same_backings(&short));
    }
}

pub type MeshKey = (u64, u32);

#[derive(Clone)]
pub struct SceneMesh {
    pub revision: u64,
    pub flags: u32,
    /// Absolute source origin. Grid ownership is resolved before camera-relative narrowing.
    pub origin: [f64; 3],
    pub triangles: MeshGeometry,
}

/// One complete dynamic frame; its identity is independent of static scene changes.
#[derive(Clone, Default)]
pub struct DynamicScene {
    pub revision: u64,
    /// Absolute source origin; camera rebasing does not change spatial membership.
    pub origin: [f64; 3],
    pub triangles: Arc<Vec<Triangle>>,
}

/// Immutable local geometry, shared by any number of persistent instances.
#[derive(Clone, Debug)]
pub struct Prototype {
    pub revision: u64,
    pub triangles: Arc<[Triangle]>,
    pub bounds: [[f32; 3]; 2],
}

/// Actual source transform and material values. The camera is never part of this identity.
#[derive(Clone, Debug, PartialEq)]
pub struct Instance {
    pub revision: u64,
    pub prototype_id: u64,
    pub origin: [f64; 3],
    /// Row-major 3x4 affine: world = origin + transform * [local, 1].
    pub transform: [f32; 12],
    /// u32::MAX inherits the prototype triangle's texture; zero means white.
    pub texture_id: u32,
    /// u32::MAX inherits the prototype triangle's material flags.
    pub flags: u32,
    /// Source RGBA bytes, multiplied with each vertex using integer floor(a*b/255).
    pub tint: [u8; 4],
    /// [scale_u, scale_v, offset_u, offset_v], applied to prototype UVs.
    pub uv_transform: [f32; 4],
}

/// Borrowed by the renderer; maps stay in their CPU owner and are never cloned per frame.
#[derive(Default, Debug)]
pub struct InstanceScene {
    pub epoch: u64,
    pub resource_revision: u64,
    pub instance_revision: u64,
    pub prototypes: BTreeMap<u64, Prototype>,
    pub instances: BTreeMap<u64, Instance>,
}

#[derive(Default)]
pub struct Scene {
    pub revision: u64,
    pub epoch: u64,
    /// Explicit catalog replacements revoke old terrain even when a consumer defers rebuilds.
    pub terrain_resource_generation: u64,
    pub resources: crate::incremental::ResourceIdentity,
    pub anchor: [f64; 3],
    pub meshes: BTreeMap<MeshKey, SceneMesh>,
    /// Only cells with all 64 complete source sections may publish static geometry.
    /// Direct renderer fixtures must explicitly declare their complete cells too.
    pub ready_terrain: BTreeSet<Cell>,
    pub textures: BTreeMap<u32, Texture>,
    pub dynamic: DynamicScene,
}

impl Scene {
    pub fn triangle_count(&self) -> usize {
        self.meshes
            .values()
            .map(|mesh| mesh.triangles.len())
            .sum::<usize>()
            + self.dynamic.triangles.len()
    }
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Camera {
    pub position: [f32; 3],
    pub forward: [f32; 3],
    pub right: [f32; 3],
    pub up: [f32; 3],
    pub vertical_fov_radians: f32,
}

/// CPU source mesh retains section-local positions until frame-space translation.
#[derive(Clone)]
pub(crate) struct Mesh {
    pub revision: MeshVersion,
    pub origin: [f64; 3],
    pub triangles: MeshGeometry,
    pub bounds: [[f32; 3]; 2],
    pub texture_id: u32,
    pub flags: u32,
}

/// Admission order, including identical content observations and removals.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, PartialOrd, Ord)]
pub(crate) struct SectionSequence(pub(crate) u64);

/// The observation that last changed rendered content. An identical observation
/// advances SectionSequence without replacing this value or the immutable mesh.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct MeshVersion(SectionSequence);

impl MeshVersion {
    pub fn captured(sequence: SectionSequence) -> Self {
        Self(sequence)
    }
    pub fn observed_at(self) -> SectionSequence {
        self.0
    }
    pub fn number(self) -> u64 {
        self.0.0
    }
}

#[derive(Default)]
pub(crate) struct DynamicMesh {
    pub texture_ids: BTreeSet<u32>,
    /// Last accepted observation, independently of the last changed geometry.
    pub sequence: u64,
    pub revision: u64,
    /// Owned validated op6 payload (origin, descriptors and source bytes), excluding its sequence.
    pub source: Vec<u8>,
    pub origin: [f64; 3],
    pub triangles: Arc<Vec<Triangle>>,
    pub bounds: [[f32; 3]; 2],
}

#[derive(Default)]
pub struct SourceScene {
    pub(crate) id: crate::incremental::ContextId,
    pub(crate) epoch: u64,
    pub(crate) revision: u64,
    pub(crate) terrain_resource_generation: u64,
    pub(crate) resources: crate::incremental::ResourceIdentity,
    pub(crate) meshes: BTreeMap<(u64, u32), Mesh>,
    /// Complete source snapshots, including observed empty sections; absence is unknown.
    pub(crate) sections: TerrainAvailability,
    /// Latest complete replacement/removal sequence, independent of content revisions.
    pub(crate) removed: BTreeMap<u64, SectionSequence>,
    pub(crate) section_completed: SectionSequence,
    pub(crate) textures: BTreeMap<u32, Texture>,
    pub(crate) triangle_count: usize,
    pub(crate) texture_memory: crate::texture_lifetime::TextureMemory,
    pub(crate) texture_lifetime: crate::texture_lifetime::TextureLifetime,
    pub(crate) dynamic: DynamicMesh,
    pub(crate) dynamic_spares: Vec<Arc<Vec<Triangle>>>,
    pub(crate) instances: InstanceContext,
    #[cfg(any(test, feature = "legacy-fixtures"))]
    pub(crate) section_scratch: crate::protocol::SectionScratch,
    pub(crate) routing: crate::routing::SourceRoutes,
    pub(crate) edits: crate::incremental::SourceEdits,
}

impl SourceScene {
    pub fn with_workers(workers: Arc<crate::workers::CpuWorkers>) -> Self {
        Self {
            routing: crate::routing::SourceRoutes::with_workers(workers),
            ..Self::default()
        }
    }

    pub fn cpu_workers(&self) -> Option<&Arc<crate::workers::CpuWorkers>> {
        self.routing.workers()
    }

    pub fn resource_generation(&self) -> u64 {
        self.resources.generation()
    }

    pub fn is_resource_texture(&self, id: u32) -> bool {
        self.texture_lifetime.resident.contains(&id)
    }

    /// A world reset drops scene consumers, but retains the prepared resource generation.
    pub fn reset_world(&mut self, epoch: u64) -> Result<(), String> {
        if epoch <= self.epoch {
            return Err("reset epoch must increase".into());
        }
        let revision = self
            .revision
            .checked_add(1)
            .ok_or("scene revision exhausted")?;
        let workers = self.routing.workers().cloned();
        let resources = self.resources;
        let mut textures = std::mem::take(&mut self.textures);
        textures.retain(|id, _| self.texture_lifetime.resident.contains(id));
        let mut texture_memory = crate::texture_lifetime::TextureMemory::default();
        let mut texture_lifetime = crate::texture_lifetime::TextureLifetime::default();
        for (&id, texture) in &textures {
            texture_memory.replace(None, Some(texture));
            texture_lifetime.pin(id);
        }
        *self = Self {
            epoch,
            revision,
            resources,
            textures,
            texture_memory,
            texture_lifetime,
            instances: InstanceContext::new(epoch),
            routing: workers
                .map_or_else(Default::default, crate::routing::SourceRoutes::with_workers),
            ..Self::default()
        };
        Ok(())
    }

    /// A new resource generation is validated as a whole before old scene consumers are
    /// revoked. Same-generation additions and animation views retain scene geometry.
    pub fn publish_resource_textures(
        &mut self,
        generation: u64,
        textures: Vec<(u32, Texture)>,
    ) -> Result<(), String> {
        if generation == 0 || generation < self.resource_generation() {
            return Err("stale resource generation".into());
        }
        if generation == self.resource_generation() {
            if textures.iter().any(|(id, _)| {
                self.textures.contains_key(id) && !self.texture_lifetime.resident.contains(id)
            }) {
                return Err("resource identity conflicts with dynamic texture".into());
            }
            let ids: Vec<_> = textures.iter().map(|(id, _)| *id).collect();
            self.set_textures(textures)?;
            for id in ids {
                self.texture_lifetime.pin(id);
            }
            return Ok(());
        }

        let revision = self
            .revision
            .checked_add(1)
            .ok_or("scene revision exhausted")?;
        let terrain_resource_generation = self
            .terrain_resource_generation
            .checked_add(1)
            .ok_or("terrain resource generation exhausted")?;
        let mut next = BTreeMap::new();
        for (id, texture) in textures {
            if id == 0 || id == u32::MAX || next.contains_key(&id) {
                return Err("invalid/duplicate resource texture identity".into());
            }
            texture.validate()?;
            next.insert(id, texture);
        }
        let resident: BTreeSet<_> = next.keys().copied().collect();
        for (&id, texture) in &self.textures {
            if !self.texture_lifetime.resident.contains(&id) {
                if next.contains_key(&id) && id != 1 {
                    return Err("resource identity conflicts with dynamic texture".into());
                }
                next.entry(id).or_insert_with(|| texture.clone());
            }
        }
        let mut texture_memory = crate::texture_lifetime::TextureMemory::default();
        texture_memory.capacity(next.values().map(|texture| (None, texture)))?;
        for texture in next.values() {
            texture_memory.replace(None, Some(texture));
        }
        let mut texture_lifetime = crate::texture_lifetime::TextureLifetime::default();
        for id in resident {
            texture_lifetime.pin(id);
        }
        texture_lifetime.inherit_retirements(&self.texture_lifetime);
        let workers = self.routing.workers().cloned();
        *self = Self {
            epoch: self.epoch,
            revision,
            terrain_resource_generation,
            resources: self.resources.with_generation(generation),
            textures: next,
            texture_memory,
            texture_lifetime,
            instances: InstanceContext::new(self.epoch),
            routing: workers
                .map_or_else(Default::default, crate::routing::SourceRoutes::with_workers),
            ..Self::default()
        };
        Ok(())
    }

    pub fn texture(&self, id: u32) -> Option<&Texture> {
        self.textures.get(&id)
    }
    /// Immutable source resources and animation frames use the existing texture delta journal.
    pub fn set_texture(&mut self, id: u32, texture: Texture) -> Result<(), String> {
        self.set_textures(vec![(id, texture)])
    }
    /// Validate the complete resource batch before advancing the scene or its delta journal.
    pub fn set_textures(&mut self, mut textures: Vec<(u32, Texture)>) -> Result<(), String> {
        self.validate_textures(&textures)?;
        // Re-publication renews source ownership even when immutable content is unchanged.
        for (id, _) in &textures {
            self.texture_lifetime.owned(*id);
        }
        textures.retain(|(id, t)| self.textures.get(id).is_none_or(|old| !old.same(t)));
        if textures.is_empty() {
            return Ok(());
        }
        let revision = self.revision + 1;
        for (id, texture) in textures {
            self.texture_memory
                .replace(self.textures.get(&id), Some(&texture));
            self.textures.insert(id, texture);
            self.edits.textures.insert(id);
        }
        self.revision = revision;
        Ok(())
    }
    pub fn validate_textures(&self, textures: &[(u32, Texture)]) -> Result<usize, String> {
        let mut ids = BTreeSet::new();
        for (id, texture) in textures {
            if *id == 0 || *id == u32::MAX || !ids.insert(*id) {
                return Err("invalid/duplicate texture identity".into());
            }
            texture.validate()?;
        }
        self.revision
            .checked_add(1)
            .ok_or("scene revision exhausted")?;
        self.texture_memory
            .capacity(textures.iter().map(|(id, t)| (self.textures.get(id), t)))
    }

    pub fn epoch(&self) -> u64 {
        self.epoch
    }

    pub fn revision(&self) -> u64 {
        self.revision
    }

    pub fn instances(&self) -> &InstanceScene {
        self.instances.scene()
    }

    pub fn instance_input(&self) -> crate::instances::InstanceInput<'_> {
        self.instances.input()
    }

    pub fn instance_sequence(&self) -> u64 {
        self.instances.sequence()
    }

    pub fn translate(&self, anchor: [f64; 3]) -> Result<Scene, String> {
        let mut meshes = BTreeMap::new();
        for (key, mesh) in &self.meshes {
            if mesh.triangles.is_empty() {
                continue;
            }
            if mesh.texture_id != 0 && !self.textures.contains_key(&mesh.texture_id) {
                return Err("mesh references a texture that has not been captured".into());
            }
            let offset = std::array::from_fn::<_, 3, _>(|i| mesh.origin[i] - anchor[i]);
            for bound in mesh.bounds {
                for i in 0..3 {
                    if (offset[i] + f64::from(bound[i])).abs() > 1_048_576.0 {
                        return Err(
                            "scene exceeds the supported camera-relative coordinate range".into(),
                        );
                    }
                }
            }
            meshes.insert(
                *key,
                SceneMesh {
                    revision: mesh.revision.number(),
                    flags: mesh.flags,
                    origin: mesh.origin,
                    triangles: mesh.triangles.clone(),
                },
            );
        }
        Ok(Scene {
            revision: self.revision,
            epoch: self.epoch,
            terrain_resource_generation: self.terrain_resource_generation,
            resources: self.resources,
            anchor,
            meshes,
            ready_terrain: self.sections.ready.clone(),
            textures: self.textures.clone(),
            dynamic: self.translate_dynamic(anchor)?,
        })
    }

    /// Last changed op6 content. Identical observations still consume their source sequence.
    pub fn dynamic_revision(&self) -> u64 {
        self.dynamic.revision
    }

    /// Constant work: vertices and texture references were validated when the frame was submitted.
    pub fn translate_dynamic(&self, anchor: [f64; 3]) -> Result<DynamicScene, String> {
        let offset = std::array::from_fn::<_, 3, _>(|i| self.dynamic.origin[i] - anchor[i]);
        if !self.dynamic.triangles.is_empty() {
            for bound in self.dynamic.bounds {
                for i in 0..3 {
                    if (offset[i] + f64::from(bound[i])).abs() > 1_048_576.0 {
                        return Err(
                            "dynamic scene exceeds the supported camera-relative coordinate range"
                                .into(),
                        );
                    }
                }
            }
        }
        Ok(DynamicScene {
            revision: self.dynamic.revision,
            origin: self.dynamic.origin,
            triangles: self.dynamic.triangles.clone(),
        })
    }
}

#[cfg(test)]
#[path = "resource_tests.rs"]
mod resource_tests;
