"""Generate native DTOs and FFM bindings from the project's restricted C POD contract.

The independent C11 compiler probe validates the target layout; this generator supports
only fixed-width scalar fields, pointers, fixed arrays, and previously declared structs.
"""
from pathlib import Path
import argparse
import re
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
HEADER = ROOT / "crates/prime-engine/include/prime.h"
SCALARS = {
    "uint8_t": (1, "u8", "byte", "JAVA_BYTE"),
    "int32_t": (4, "i32", "int", "JAVA_INT"),
    "uint32_t": (4, "u32", "int", "JAVA_INT"),
    "int64_t": (8, "i64", "long", "JAVA_LONG"),
    "uint64_t": (8, "u64", "long", "JAVA_LONG"),
    "float": (4, "f32", "float", "JAVA_FLOAT"),
    "double": (8, "f64", "double", "JAVA_DOUBLE"),
}


def read_header(path):
    text = path.read_text(encoding="utf-8")
    return re.sub(r'#include "([^"]+)"', lambda m: read_header(path.parent / m[1]), text)


def generate():
    source = re.sub(r"/\*.*?\*/|//[^\n]*", "", read_header(HEADER), flags=re.S)
    constants = re.findall(r"^#define\s+(PRIME_\w+)\s+(0x[0-9A-Fa-f]+|\d+)\s*$", source, re.M)
    types = {}
    structs = []
    for m in re.finditer(r"typedef\s+struct\s+(\w+)\s*\{([^}]+)\}\s*(\w+)\s*;", source, re.S):
        name, body, alias = m.groups()
        if name != alias:
            raise ValueError(f"Use matching struct tag/typedef: {name}")
        fields = []
        size, align = 0, 1
        for declaration in body.split(";"):
            if not declaration.strip():
                continue
            f = re.fullmatch(r"\s*(const\s+)?(\w+)\s*(\*)?\s*(\w+)\s*(?:\[(\d+)\])?\s*", declaration)
            if not f:
                raise ValueError(f"Unsupported C field: {declaration}")
            const, kind, pointer, field, count = f.groups()
            count = int(count) if count else None
            if pointer:
                fs, fa = 8, 8
            elif kind in SCALARS:
                fs = fa = SCALARS[kind][0]
            else:
                fs, fa = types[kind]
            size = (size + fa - 1) // fa * fa
            fields.append((kind, bool(pointer), bool(const), field, count, size, fs, fa))
            size += fs * (count or 1)
            align = max(align, fa)
        size = (size + align - 1) // align * align
        types[name] = size, align
        structs.append((name, fields, size, align))

    rust = ["// Generated by scripts/generate-abi.py; edit C headers, not this file.",
            "// Uniform explicit defaults also support fixed arrays larger than Rust Default derives.",
            "#![allow(clippy::derivable_impls)]"]
    java = ["// Generated by scripts/generate-abi.py; edit C headers, not this file.",
            "package dev.primept.abi;", "", "import java.lang.foreign.*;",
            "import java.lang.invoke.MethodHandle;", "import static java.lang.foreign.ValueLayout.*;",
            "", "public final class PrimeAbi {", "    private PrimeAbi() {}"]
    probe = ['#include <stddef.h>', '#include <stdio.h>', '#include "prime.h"',
             'int main(void) {', '    _Static_assert(sizeof(void *) == 8, "Prime requires 64-bit pointers");']
    expected = {}
    for name, value in constants:
        rust.append(f"pub const {name}: u32 = {value};")
        java.append(f"    public static final int {name} = {value};")
    for name, fields, size, align in structs:
        rust += ["", "#[repr(C)]", "#[derive(Clone, Copy, Debug)]", f"pub struct {name} {{"]
        java += [f"    public static final class {name} {{", f"        private {name}() {{}}",
                 f"        public static final long SIZE = {size}, ALIGN = {align};"]
        layouts = []
        end = 0
        defaults = []
        for kind, pointer, const, field, count, offset, fs, fa in fields:
            rt = ("*const " if const else "*mut ") + ("std::ffi::c_void" if kind == "void" else SCALARS.get(kind, (0, kind))[1]) if pointer else SCALARS.get(kind, (0, kind))[1]
            rt = f"[{rt}; {count}]" if count else rt
            rust.append(f"    pub {field}: {rt},")
            default = ("std::ptr::null()" if const else "std::ptr::null_mut()") if pointer else ("0.0" if kind in ("float", "double") else "0" if kind in SCALARS else f"{kind}::default()")
            defaults.append(f"            {field}: " + (f"[{default}; {count}]" if count else default) + ",")
            if offset > end:
                layouts.append(f"MemoryLayout.paddingLayout({offset-end})")
            layout = "ADDRESS" if pointer else SCALARS[kind][3] if kind in SCALARS else f"{kind}.LAYOUT"
            if count:
                layout = f"MemoryLayout.sequenceLayout({count}, {layout})"
            layouts.append(f'{layout}.withName("{field}")')
            end = offset + fs * (count or 1)
        if end < size:
            layouts.append(f"MemoryLayout.paddingLayout({size-end})")
        java += ["        public static final MemoryLayout LAYOUT = MemoryLayout.structLayout(",
                 "                " + ",\n                ".join(layouts) + f').withName("{name}");']
        java += ["        static {", f'            if (LAYOUT.byteSize() != SIZE || LAYOUT.byteAlignment() != ALIGN) throw new ExceptionInInitializerError("{name} layout");']
        for _, _, _, field, _, offset, _, _ in fields:
            java.append(f'            if (LAYOUT.byteOffset(MemoryLayout.PathElement.groupElement("{field}")) != {offset}) throw new ExceptionInInitializerError("{name}.{field} offset");')
        java.append("        }")
        for kind, pointer, const, field, count, offset, fs, fa in fields:
            index = ", long index" if count else ""
            at = f"{offset}L" + (f" + Math.multiplyExact(java.util.Objects.checkIndex(index, {count}L), {fs}L)" if count else "")
            if not pointer and kind not in SCALARS:
                java.append(f"        public static MemorySegment {field}(MemorySegment value{index}) {{ return value.asSlice({at}, {fs}); }}")
            else:
                jt, jl = ("MemorySegment", "ADDRESS") if pointer else SCALARS[kind][2:]
                java.append(f"        public static {jt} {field}(MemorySegment value{index}) {{ return value.get({jl}, {at}); }}")
                java.append(f"        public static void {field}(MemorySegment value{index}, {jt} field) {{ value.set({jl}, {at}, field); }}")
        java.append("    }")
        rust += ["}", f"impl Default for {name} {{", "    fn default() -> Self {", "        Self {", *defaults, "        }", "    }", "}",
                 f"const _: () = assert!(std::mem::size_of::<{name}>() == {size});",
                 f"const _: () = assert!(std::mem::align_of::<{name}>() == {align});"]
        for field, value, expr in [("size", size, f"sizeof({name})"), ("align", align, f"_Alignof({name})")]:
            key = f"{name}.{field}"
            expected[key] = value
            probe.append(f'    printf("{key}=%zu\\n", {expr});')
        for _, _, _, field, _, offset, _, _ in fields:
            rust.append(f"const _: () = assert!(std::mem::offset_of!({name}, {field}) == {offset});")
            key = f"{name}.{field}"
            expected[key] = offset
            probe.append(f'    printf("{key}=%zu\\n", offsetof({name}, {field}));')

    functions = re.findall(r"(uint32_t|uint64_t|int32_t|void)\s+(prime_\w+)\s*\(([^;]*)\)\s*;", source)
    for result, name, arguments in functions:
        arglayouts = []
        rustargs = []
        cargs = []
        for arg in arguments.split(","):
            arg = arg.strip()
            if arg and arg != "void":
                arglayouts.append("ADDRESS" if "*" in arg else SCALARS[arg.split()[0]][3])
                m = re.fullmatch(r"(const\s+)?(\w+)\s*(\*)?\s*(\w+)", arg)
                if not m:
                    raise ValueError(f"Unsupported function argument: {arg}")
                const, kind, pointer, field = m.groups()
                rt = SCALARS.get(kind, (0,kind))[1]
                if pointer:
                    rt = ("*const " if const else "*mut ") + rt
                rustargs.append(rt)
                cargs.append(("const " if const else "") + kind + (" *" if pointer else ""))
        alias = "".join(x.capitalize() for x in name.split("_")) + "Fn"
        ret = "()" if result == "void" else SCALARS[result][1]
        rust.append(f'pub type {alias} = unsafe extern "C" fn({", ".join(rustargs)}) -> {ret};')
        probe.insert(3, f'typedef {result} (*{alias})({", ".join(cargs) if cargs else "void"});')
        probe.append(f'    _Static_assert(_Generic(&{name}, {alias}: 1, default: 0), "{name} signature");')
        factory = "ofVoid(" if result == "void" else "of(" + SCALARS[result][3] + (", " if arglayouts else "")
        java.append(f"    public static final FunctionDescriptor {name.upper()}_DESCRIPTOR = FunctionDescriptor.{factory}{', '.join(arglayouts)});")
    java += ["    public static MethodHandle bind(SymbolLookup lookup, String name) {",
             "        FunctionDescriptor descriptor = switch (name) {"]
    for _, name, _ in functions:
        java.append(f'            case "{name}" -> {name.upper()}_DESCRIPTOR;')
    java += ['            default -> throw new IllegalArgumentException("Unknown ABI symbol: " + name);',
             "        };", "        return Linker.nativeLinker().downcallHandle(",
             "                lookup.find(name).orElseThrow(() -> new UnsatisfiedLinkError(name)), descriptor);", "    }", "}"]
    probe += ["    return 0;", "}"]
    return {
        ROOT / "crates/prime-abi/src/generated.rs": "\n".join(rust) + "\n",
        ROOT / "adapters/common/src/main/java/dev/primept/abi/PrimeAbi.java": "\n".join(java) + "\n",
    }, "\n".join(probe), expected


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--probe", metavar="C_COMPILER")
    args = parser.parse_args()
    outputs, probe, expected = generate()
    for path, data in outputs.items():
        command = (["rustfmt", "--edition", "2024", "--emit", "stdout"] if path.suffix == ".rs" else
                   ["clang-format", "--style=file", "--fallback-style=none", f"--assume-filename={path}"])
        data = subprocess.run(command, input=data, text=True, capture_output=True, check=True, cwd=ROOT).stdout
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != data:
                raise SystemExit(f"Generated ABI is stale: {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(data, encoding="utf-8", newline="\n")
    if args.probe:
        with tempfile.TemporaryDirectory(prefix="prime-abi-") as directory:
            source = Path(directory) / "layout.c"
            executable = Path(directory) / "layout.exe"
            source.write_text(probe, encoding="utf-8")
            subprocess.run([args.probe, "-std=c11", "-I", str(HEADER.parent), str(source), "-o", str(executable)], check=True)
            output = subprocess.check_output([str(executable)], text=True)
            actual = {key: int(value) for key, value in (line.split("=") for line in output.splitlines())}
            if actual != expected:
                raise SystemExit(f"C compiler ABI layout mismatch: {actual}")
            print(f"C compiler verified {len(actual)} layout facts")
    print(f"ABI {'checked' if args.check else 'generated'}: {len(outputs)} files")


if __name__ == "__main__":
    main()
