"""Import the pinned Prime/Sky Tracer physical inputs without changing any float bits.

Usage: python scripts/import-atmosphere.py PATH_TO_OLD_PRIME [--output FILE]
Only the asset container changes. No NumPy or ML runtime is required.
"""

import argparse
import base64
import gzip
import hashlib
import json
from pathlib import Path
import struct


def write_tensors(path, tensors, metadata):
    header = {"__metadata__": metadata}
    payload = bytearray()
    for name, dtype, shape, data in tensors:
        start = len(payload)
        payload.extend(data)
        header[name] = {"dtype": dtype, "shape": shape,
                        "data_offsets": [start, len(payload)]}
    encoded = json.dumps(header, separators=(",", ":")).encode("utf-8")
    encoded += b" " * (-len(encoded) % 8)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(struct.pack("<Q", len(encoded)) + encoded + payload)


def main():
    workspace = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("old_prime", type=Path)
    parser.add_argument("--output", type=Path,
                        default=workspace / "artifacts/asset-inputs/atmosphere/medium.safetensors")
    args = parser.parse_args()
    source = args.old_prime / "src/client/resources/prime/atmosphere"
    meta = json.loads((source / "medium.json").read_text(encoding="utf-8"))
    assert meta["sourceCommit"] == "b66b16342afe38e788a5ece5371d3b3a67c5909a"
    medium = gzip.decompress(base64.b64decode((source / "medium.bin.gz.b64").read_bytes()))
    extinction = gzip.decompress(base64.b64decode((source / "extinction.bin.gz.b64").read_bytes()))
    assert hashlib.sha256(medium).hexdigest() == meta["sha256"]
    assert hashlib.sha256(extinction).hexdigest() == meta["extinction"]["sha256"]
    sections = [
        ("heights", [40, 4]), ("profiles", [50, 7, 4]),
        ("phase", [4, 1024, 4]), ("phase_mass", [4, 4]),
        ("states", [40, 160, 4]), ("quadrature", [1024, 4]),
        ("phase_nodes", [20, 4]), ("solar_mapping", [40, 4, 4]),
        ("optical_heights", [128, 4]), ("cone_nodes", [12, 4]),
        ("source_coefficients", [40, 6, 4]),
    ]
    tensors = []
    offset = 0
    for name, shape in sections:
        size = 4
        for count in shape:
            size *= count
        tensors.append((name, "F32", shape, medium[offset:offset + size]))
        offset += size
    assert offset == len(medium) == 199584
    tensors.append(("extinction", "F32", [50, 2, 4], extinction))
    metadata = {
        "schema": "prime.atmosphere.medium.v1",
        "source": meta["sourceCommit"], "medium_sha256": meta["sha256"],
        "wavelength_nm": "450,510,580,650", "species": "inso,waso,soot,suso",
        "phase_coordinate": "u=cbrt((1-mu)/2); nodes=(i+0.5)/1024; linear-u; clamp-endpoints",
        "phase_unit": "sr^-1", "distance_unit": "km",
        "phase_mu": "+1=forward", "density_scale": "1",
        "prime_sun_radius_radians": "0.00471", "prime_space_sun_intensity": "12.5",
        "source_parameters": json.dumps(meta["params"], separators=(",", ":")),
    }
    target = args.output
    write_tensors(target, tensors, metadata)
    print(f"Wrote {target}: {target.stat().st_size} bytes; physical f32 payload unchanged")
    fixtures = source.parents[3] / "test/resources/prime/atmosphere"
    # Frozen independent WGSL results from the pinned upstream, not regenerated by the port.
    root = Path(__file__).resolve().parents[1] / "crates/prime-vulkan/tests/fixtures"
    root.mkdir(parents=True, exist_ok=True)
    for name in ["sky", "projection", "transport"]:
        data = gzip.decompress(base64.b64decode((fixtures / f"{name}-reference.bin.gz.b64").read_bytes()))
        (root / f"atmosphere-{name}.bin").write_bytes(data)


if __name__ == "__main__":
    main()
