use prime_scene::{
    protocol::{Frame, MAGIC},
    scene::SourceScene,
};

fn header(op: u32, epoch: u64) -> Vec<u8> {
    let mut bytes = Vec::new();
    for value in [MAGIC, prime_scene::protocol::ABI_VERSION, op, 0] {
        bytes.extend(value.to_le_bytes());
    }
    bytes.extend(epoch.to_le_bytes());
    bytes
}
fn mesh(revision: u64, layer: u32) -> Vec<u8> {
    let mut bytes = header(8, 1);
    bytes.extend(91u64.to_le_bytes());
    bytes.extend(revision.to_le_bytes());
    for value in [29_999_984.0_f64, 64.0, -16.0] {
        bytes.extend(value.to_le_bytes());
    }
    for value in [1u32, 0, layer, 0, 0, 4, 4, 28, 0, 12, 16, 0] {
        bytes.extend(value.to_le_bytes());
    }
    for xyz in [
        [0.125_f32, 0.0, 0.0],
        [1.0, 0.0, 0.0],
        [1.0, 1.0, 0.0],
        [0.125, 1.0, 0.0],
    ] {
        for value in xyz {
            bytes.extend(value.to_le_bytes());
        }
        bytes.extend([128, 64, 32, 255]);
        bytes.extend(0.25_f32.to_le_bytes());
        bytes.extend(0.75_f32.to_le_bytes());
        bytes.extend([0, 0, 240, 0]);
    }
    bytes
}
fn initialized() -> SourceScene {
    let mut source = SourceScene::default();
    source.submit(&header(1, 1)).unwrap();
    source
}

#[test]
fn decode_real_block_layout_and_rebase_before_narrowing() {
    let mut source = initialized();
    source.submit(&mesh(1, 0)).unwrap();
    let scene = source.translate([29_999_984.0, 64.0, -16.0]).unwrap();
    assert_eq!(scene.triangle_count(), 2);
    assert_eq!(
        scene.meshes[&(91, 0)].triangles.triangle(0).positions[0],
        [0.125, 0.0, 0.0]
    );
    assert_eq!(
        scene.meshes[&(91, 0)].triangles.triangle(1).positions,
        [[1.0, 1.0, 0.0], [0.125, 1.0, 0.0], [0.125, 0.0, 0.0]]
    );
    assert_eq!(
        scene.meshes[&(91, 0)].triangles.triangle(0).colors[0],
        [128.0 / 255.0, 64.0 / 255.0, 32.0 / 255.0, 1.0]
    );
    assert_eq!(
        scene.meshes[&(91, 0)].triangles.triangle(0).uvs[0],
        [0.25, 0.75]
    );
}

#[test]
fn decode_java_source_quads_24_byte_fixture_preserves_every_corner() {
    // Generated by the actual common Java SourceQuads + Packets.sectionReplace encoder:
    // epoch=1, section=91, revision=3, origin=(29999984,64,-16), CUTOUT,
    // ARGB=(ffabcdef,7f123456,01020304,ffffffff), positions/UVs below.
    // A literal packet keeps this test independent of a second Rust wire encoder.
    const PACKET: [u8; 208] = [
        0x50, 0x52, 0x50, 0x54, 0x06, 0x00, 0x00, 0x00, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x5b, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x37,
        0x9c, 0x7c, 0x41, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x50, 0x40, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x30, 0xc0, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00,
        0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x04, 0x00,
        0x00, 0x00, 0x18, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0c, 0x00, 0x00, 0x00, 0x10,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x3e, 0x00, 0x00, 0x40, 0xc0,
        0x00, 0x00, 0x10, 0x41, 0xab, 0xcd, 0xef, 0xff, 0x00, 0x00, 0x00, 0x3e, 0x00, 0x00, 0x80,
        0x3e, 0x00, 0x00, 0x90, 0x3f, 0x00, 0x00, 0x40, 0xc0, 0x00, 0x00, 0x10, 0x41, 0x12, 0x34,
        0x56, 0x7f, 0x00, 0x00, 0x40, 0x3f, 0x00, 0x00, 0x80, 0x3e, 0x00, 0x00, 0x90, 0x3f, 0x00,
        0x00, 0x00, 0xc0, 0x00, 0x00, 0x10, 0x41, 0x02, 0x03, 0x04, 0x01, 0x00, 0x00, 0x40, 0x3f,
        0x00, 0x00, 0x60, 0x3f, 0x00, 0x00, 0x00, 0x3e, 0x00, 0x00, 0x00, 0xc0, 0x00, 0x00, 0x10,
        0x41, 0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0x3e, 0x00, 0x00, 0x60, 0x3f,
    ];
    let positions = [
        [0.125, -3.0, 9.0],
        [1.125, -3.0, 9.0],
        [1.125, -2.0, 9.0],
        [0.125, -2.0, 9.0],
    ];
    let uvs = [[0.125, 0.25], [0.75, 0.25], [0.75, 0.875], [0.125, 0.875]];
    let rgba = [
        [0xab_u8, 0xcd, 0xef, 0xff],
        [0x12, 0x34, 0x56, 0x7f],
        [0x02, 0x03, 0x04, 0x01],
        [0xff, 0xff, 0xff, 0xff],
    ];

    let mut source = initialized();
    let mut atlas = header(4, 1);
    for value in [1_u32, 1, 1, 0] {
        atlas.extend(value.to_le_bytes());
    }
    atlas.extend([255; 4]);
    source.submit(&atlas).unwrap();
    source.submit(&PACKET).unwrap();
    let scene = source.translate([29_999_728.0, 64.0, -16.0]).unwrap();
    assert_eq!(scene.meshes.len(), 1);
    assert_eq!(scene.triangle_count(), 2);
    let captured = &scene.meshes[&(91, 1)];
    assert_eq!(captured.revision, 3);
    assert_eq!(captured.flags, 1);
    assert_eq!(captured.origin, [29_999_984.0, 64.0, -16.0]);
    for (triangle, corners) in captured.triangles.iter().zip([[0, 1, 2], [2, 3, 0]]) {
        assert_eq!(triangle.texture_id, 1);
        assert_eq!(triangle.flags, 1);
        for (corner, source_vertex) in corners.into_iter().enumerate() {
            assert_eq!(triangle.positions[corner], positions[source_vertex]);
            assert_eq!(triangle.uvs[corner], uvs[source_vertex]);
            // Encoded RGB is normalized without EOTF or raster lighting; alpha is independent.
            assert_eq!(
                triangle.colors[corner],
                rgba[source_vertex].map(|channel| f32::from(channel) / 255.0)
            );
        }
    }
}

#[test]
fn every_truncated_mesh_is_rejected_without_publication() {
    let bytes = mesh(2, 0);
    let mut source = initialized();
    source.submit(&mesh(1, 0)).unwrap();
    let revision = source.revision();
    for length in 0..bytes.len() {
        assert!(
            source.submit(&bytes[..length]).is_err(),
            "accepted prefix {length}"
        );
        assert_eq!(source.revision(), revision);
    }
    assert_eq!(
        source
            .translate([29_999_984.0, 64.0, -16.0])
            .unwrap()
            .triangle_count(),
        2
    );
}

#[test]
fn malformed_input_cannot_partially_replace_geometry() {
    let mut source = initialized();
    source.submit(&mesh(1, 0)).unwrap();
    for (offset, value) in [
        (112, f32::NAN.to_bits()),
        (92, 0u32),
        (88, u32::MAX),
        (80, 3u32),
    ] {
        let mut bytes = mesh(2, 0);
        bytes[offset..offset + 4].copy_from_slice(&value.to_le_bytes());
        assert!(source.submit(&bytes).is_err());
    }
    assert_eq!(source.revision(), 2);
}

#[test]
fn section_tombstone_prevents_resurrection_of_any_layer() {
    let mut source = initialized();
    source.submit(&mesh(1, 0)).unwrap();
    let mut remove = header(3, 1);
    remove.extend(91u64.to_le_bytes());
    remove.extend(3u64.to_le_bytes());
    source.submit(&remove).unwrap();
    assert!(source.submit(&mesh(2, 1)).is_err());
    source.submit(&mesh(4, 0)).unwrap();
    assert!(source.submit(&mesh(4, 1)).is_err());
    assert!(source.submit(&remove).is_err());
    assert!(source.submit(&mesh(4, 0)).is_err());
    source.submit(&header(1, 2)).unwrap();
    assert!(source.submit(&mesh(5, 0)).is_err());
    assert!(source.translate([0.0; 3]).unwrap().meshes.is_empty());
}

#[test]
fn texture_length_and_identity_are_checked() {
    let mut source = initialized();
    let mut bytes = header(4, 1);
    for value in [1u32, 1, 1, 0] {
        bytes.extend(value.to_le_bytes());
    }
    bytes.extend([20, 40, 80, 128]);
    source.submit(&bytes).unwrap();
    let scene = source.translate([0.0; 3]).unwrap();
    assert_eq!(scene.textures[&1].pixels.as_ref(), &[20, 40, 80, 128]);
    bytes.push(0);
    assert!(source.submit(&bytes).is_err());
    assert_eq!(source.revision(), 2);
}

#[test]
fn snapshots_share_immutable_vertices_across_rebases_and_keep_old_versions_alive() {
    let mut source = initialized();
    source.submit(&mesh(1, 0)).unwrap();
    let first = source.translate([29_999_984.0, 64.0, -16.0]).unwrap();
    let shifted = source.translate([29_999_728.0, 64.0, -16.0]).unwrap();
    assert!(prime_scene::geometry::MeshGeometry::ptr_eq(
        &first.meshes[&(91, 0)].triangles,
        &shifted.meshes[&(91, 0)].triangles
    ));
    assert_eq!(
        shifted.meshes[&(91, 0)].origin,
        first.meshes[&(91, 0)].origin
    );
    assert_eq!(shifted.meshes[&(91, 0)].origin, [29_999_984.0, 64.0, -16.0]);
    let mut changed = mesh(2, 0);
    changed[112..116].copy_from_slice(&0.5_f32.to_le_bytes());
    source.submit(&changed).unwrap();
    let latest = source.translate([29_999_984.0, 64.0, -16.0]).unwrap();
    assert_eq!(
        first.meshes[&(91, 0)].triangles.triangle(0).positions[0][0],
        0.125
    );
    assert_eq!(
        latest.meshes[&(91, 0)].triangles.triangle(0).positions[0][0],
        0.5
    );
}

#[test]
fn absent_section_removal_preserves_render_revision_but_blocks_stale_geometry() {
    let mut source = initialized();
    let revision = source.revision();
    let mut remove = header(3, 1);
    remove.extend(91u64.to_le_bytes());
    remove.extend(3u64.to_le_bytes());
    source.submit(&remove).unwrap();
    assert_eq!(source.revision(), revision);
    assert!(source.submit(&mesh(2, 0)).is_err());
    source.submit(&mesh(4, 0)).unwrap();
    assert_eq!(
        source
            .translate([29_999_984.0, 64.0, -16.0])
            .unwrap()
            .triangle_count(),
        2
    );
}

#[test]
fn frame_rejects_non_orthogonal_camera_and_invalid_extent() {
    let mut bytes = header(5, 1);
    for value in [30_000_000.0_f64, 70.0, -10.0] {
        bytes.extend(value.to_le_bytes());
    }
    for value in [0.0_f32, 0.0, -1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0] {
        bytes.extend(value.to_le_bytes());
    }
    for value in [640u32, 360, 0, 0] {
        bytes.extend(value.to_le_bytes());
    }
    let frame = Frame::parse(&bytes).unwrap();
    assert_eq!(frame.output_len(), 640 * 360 * 4);
    assert_eq!(
        frame.relative_camera(frame.anchor()).position,
        [128.0, 70.0, 246.0]
    );
    for width in [4097_u32, 65536] {
        bytes[88..92].copy_from_slice(&width.to_le_bytes());
        let wide = Frame::parse(&bytes).unwrap();
        assert_eq!(wide.output_len(), width as usize * 360 * 4);
    }
    bytes[88..92].copy_from_slice(&u32::MAX.to_le_bytes());
    assert!(Frame::parse(&bytes).is_err());
    bytes[88..92].copy_from_slice(&640u32.to_le_bytes());
    bytes[60..64].copy_from_slice(&0.0_f32.to_le_bytes());
    assert!(Frame::parse(&bytes).is_err());
}

fn dynamic_span(texture: u32, flags: u32, topology: u32) -> Vec<u8> {
    let mut bytes = Vec::new();
    for value in [texture, flags, topology, topology, 24, 0, 12, 16] {
        bytes.extend(value.to_le_bytes());
    }
    for vertex in 0..topology {
        for value in [vertex as f32 + 0.125, 2.0, -3.0] {
            bytes.extend(value.to_le_bytes());
        }
        bytes.extend([128 + vertex as u8, 64, 32, 127]);
        bytes.extend(0.25_f32.to_le_bytes());
        bytes.extend(0.75_f32.to_le_bytes());
    }
    bytes
}

fn dynamic(epoch: u64, sequence: u64, spans: &[Vec<u8>]) -> Vec<u8> {
    let mut bytes = header(6, epoch);
    bytes.extend(sequence.to_le_bytes());
    for value in [29_999_984.0_f64, 64.0, -16.0] {
        bytes.extend(value.to_le_bytes());
    }
    bytes.extend((spans.len() as u32).to_le_bytes());
    bytes.extend(0_u32.to_le_bytes());
    for span in spans {
        bytes.extend(span);
    }
    bytes
}

#[test]
fn dynamic_frames_replace_atomically_without_invalidating_static_geometry() {
    let anchor = [29_999_984.0, 64.0, -16.0];
    let mut source = initialized();
    source.submit(&mesh(1, 0)).unwrap();
    let static_revision = source.revision();
    let static_scene = source.translate(anchor).unwrap();
    source
        .submit(&dynamic(
            1,
            1,
            &[
                dynamic_span(0, 0, 3),
                dynamic_span(0, 1, 4),
                dynamic_span(0, 2, 4),
            ],
        ))
        .unwrap();
    let scene = source.translate(anchor).unwrap();
    assert_eq!(source.revision(), static_revision);
    assert_eq!(scene.dynamic.revision, 1);
    assert_eq!(scene.dynamic.triangles.len(), 5);
    assert_eq!(scene.triangle_count(), 7);
    assert!(prime_scene::geometry::MeshGeometry::ptr_eq(
        &static_scene.meshes[&(91, 0)].triangles,
        &scene.meshes[&(91, 0)].triangles
    ));
    assert_eq!(
        scene
            .dynamic
            .triangles
            .iter()
            .map(|t| t.flags)
            .collect::<Vec<_>>(),
        [0, 1, 1, 2, 2]
    );
    let quad_second = &scene.dynamic.triangles[2];
    assert_eq!(
        quad_second.positions,
        [[2.125, 2.0, -3.0], [3.125, 2.0, -3.0], [0.125, 2.0, -3.0]]
    );
    assert_eq!(
        quad_second.colors[0],
        [130.0 / 255.0, 64.0 / 255.0, 32.0 / 255.0, 127.0 / 255.0]
    );
    assert_eq!(quad_second.uvs[0], [0.25, 0.75]);
    let rebased = source
        .translate_dynamic([29_999_728.0, 64.0, -16.0])
        .unwrap();
    assert_eq!(rebased.origin, [29_999_984.0, 64.0, -16.0]);
    assert!(std::sync::Arc::ptr_eq(
        &scene.dynamic.triangles,
        &rebased.triangles
    ));
    assert!(source.translate_dynamic([0.0; 3]).is_err());

    source.submit(&dynamic(1, 2, &[])).unwrap();
    let empty = source.translate(anchor).unwrap();
    assert_eq!(source.revision(), static_revision);
    assert_eq!(empty.dynamic.revision, 2);
    assert_eq!(empty.triangle_count(), 2);
    assert!(empty.dynamic.triangles.is_empty());
    assert_eq!(scene.dynamic.triangles.len(), 5); // Earlier snapshots keep their own immutable lease.
}

#[test]
fn every_truncated_dynamic_frame_and_late_invalid_span_preserves_the_previous_frame() {
    let anchor = [29_999_984.0, 64.0, -16.0];
    let mut source = initialized();
    source
        .submit(&dynamic(1, 7, &[dynamic_span(0, 1, 4)]))
        .unwrap();
    let before = source.translate_dynamic(anchor).unwrap();
    let static_revision = source.revision();
    let candidate = dynamic(1, 8, &[dynamic_span(0, 2, 4), dynamic_span(0, 0, 3)]);
    for length in 0..candidate.len() {
        assert!(
            source.submit(&candidate[..length]).is_err(),
            "accepted prefix {length}"
        );
        assert_eq!(source.dynamic_revision(), 7);
        assert_eq!(source.revision(), static_revision);
    }
    let second_span = 64 + 32 + 4 * 24;
    let mut bad = candidate.clone();
    bad[second_span + 32..second_span + 36].copy_from_slice(&f32::NAN.to_le_bytes());
    assert!(source.submit(&bad).is_err());
    let mut trailing = candidate.clone();
    trailing.push(0);
    assert!(source.submit(&trailing).is_err());
    let after = source.translate_dynamic(anchor).unwrap();
    assert_eq!(after.revision, 7);
    assert!(std::sync::Arc::ptr_eq(&before.triangles, &after.triangles));
    source.submit(&candidate).unwrap(); // Failed publication did not consume its sequence.
    assert_eq!(source.dynamic_revision(), 8);
}

#[test]
fn dynamic_layout_flags_and_nonfinite_values_are_rejected_without_publication() {
    let mut source = initialized();
    let valid = dynamic(1, 1, &[dynamic_span(0, 1, 4)]);
    for (offset, value) in [
        (60, 1_u32),
        (68, 3),
        (72, 0),
        (76, 5),
        (80, 0),
        (84, u32::MAX),
        (88, u32::MAX),
        (92, u32::MAX),
        (96, f32::NAN.to_bits()),
        (96, 4096.5_f32.to_bits()),
        (112, f32::INFINITY.to_bits()),
    ] {
        let mut bad = valid.clone();
        bad[offset..offset + 4].copy_from_slice(&value.to_le_bytes());
        assert!(
            source.submit(&bad).is_err(),
            "accepted invalid field at {offset}"
        );
        assert_eq!(source.dynamic_revision(), 0);
        assert_eq!(source.revision(), 1);
    }
    for origin in [f64::NAN, f64::INFINITY, 32_000_001.0] {
        let mut bad = valid.clone();
        bad[32..40].copy_from_slice(&origin.to_le_bytes());
        assert!(source.submit(&bad).is_err());
    }
    source.submit(&valid).unwrap();
}

#[test]
fn dynamic_sequences_are_independent_and_restart_only_after_epoch_reset() {
    let mut source = initialized();
    let revision = source.revision();
    source.submit(&dynamic(1, 2, &[])).unwrap();
    assert_eq!(source.revision(), revision);
    for (epoch, sequence) in [(1, 0), (1, 1), (1, 2), (0, 3), (2, 3)] {
        assert!(source.submit(&dynamic(epoch, sequence, &[])).is_err());
    }
    source.submit(&header(1, 2)).unwrap();
    assert_eq!(source.dynamic_revision(), 0);
    assert!(source.submit(&dynamic(1, 3, &[])).is_err());
    source.submit(&dynamic(2, 1, &[])).unwrap();
    assert_eq!(source.dynamic_revision(), 1);
    assert_eq!(source.revision(), revision + 1);
}

#[test]
fn dynamic_texture_references_require_prior_capture_and_do_not_partially_replace() {
    let mut source = initialized();
    let packet = dynamic(1, 1, &[dynamic_span(0, 0, 3), dynamic_span(17, 2, 4)]);
    assert!(source.submit(&packet).is_err());
    assert_eq!(source.dynamic_revision(), 0);
    let mut texture = header(4, 1);
    for value in [17_u32, 1, 1, 0] {
        texture.extend(value.to_le_bytes());
    }
    texture.extend([20, 40, 80, 128]);
    source.submit(&texture).unwrap();
    source.submit(&packet).unwrap();
    let scene = source.translate([29_999_984.0, 64.0, -16.0]).unwrap();
    assert_eq!(scene.dynamic.triangles[1].texture_id, 17);
    assert_eq!(scene.dynamic.triangles[1].flags, 2);
}

#[test]
fn static_alpha_blend_is_distinct_from_cutout() {
    let mut source = initialized();
    let mut translucent = mesh(1, 2);
    translucent[80..84].copy_from_slice(&2_u32.to_le_bytes());
    source.submit(&translucent).unwrap();
    let scene = source.translate([29_999_984.0, 64.0, -16.0]).unwrap();
    assert_eq!(scene.meshes[&(91, 2)].flags, 2);
    assert!(
        scene.meshes[&(91, 2)]
            .triangles
            .iter()
            .all(|triangle| triangle.flags == 2)
    );
}

#[test]
fn dynamic_storage_reuses_only_after_real_snapshot_consumers_release() {
    use prime_scene::incremental::TranslatedScene;
    use std::collections::BTreeSet;
    let mut source = initialized();
    let mut translated = TranslatedScene::default();
    let spans = [dynamic_span(0, 0, 4)];
    let mut addresses = BTreeSet::new();
    for sequence in 1..=50 {
        source.submit(&dynamic(1, sequence, &spans)).unwrap();
        translated
            .update(&mut source, [29_999_984.0, 64.0, -16.0])
            .unwrap();
        addresses.insert(translated.input().dynamic.triangles.as_ptr() as usize);
    }
    assert!(
        addresses.len() <= 2,
        "the live source and its next unpublished workspace alternate"
    );
    let frozen = source.translate([29_999_984.0, 64.0, -16.0]).unwrap();
    let retained = frozen.dynamic.triangles.as_ptr();
    for sequence in 51..=60 {
        source.submit(&dynamic(1, sequence, &spans)).unwrap();
        translated
            .update(&mut source, [29_999_984.0, 64.0, -16.0])
            .unwrap();
        assert_ne!(translated.input().dynamic.triangles.as_ptr(), retained);
    }
    assert_eq!(frozen.dynamic.triangles.len(), 2);
    let invalid = dynamic(1, 61, &spans);
    assert!(source.submit(&invalid[..invalid.len() - 1]).is_err());
    assert_eq!(source.dynamic_revision(), 60);
}

#[test]
fn retired_texture_waits_for_static_and_raw_references_and_rejects_old_abi() {
    use prime_scene::incremental::TranslatedScene;
    let mut source = initialized();
    let mut texture = header(4, 1);
    for n in [17_u32, 1, 1, 0] {
        texture.extend(n.to_le_bytes());
    }
    texture.extend([255; 4]);
    source.submit(&texture).unwrap();
    let mut section = mesh(1, 0);
    section[76..80].copy_from_slice(&17_u32.to_le_bytes());
    source.submit(&section).unwrap();
    source
        .submit(&dynamic(1, 1, &[dynamic_span(17, 0, 4)]))
        .unwrap();
    let mut retired = header(9, 1);
    for n in [1_u32, 0, 17] {
        retired.extend(n.to_le_bytes());
    }
    source.submit(&retired).unwrap();
    let mut translated = TranslatedScene::default();
    let anchor = [29_999_984.0, 64.0, -16.0];
    translated.update(&mut source, anchor).unwrap();
    assert!(translated.input().textures.contains_key(&17));
    let mut remove = header(3, 1);
    remove.extend(91_u64.to_le_bytes());
    remove.extend(2_u64.to_le_bytes());
    source.submit(&remove).unwrap();
    translated.update(&mut source, anchor).unwrap();
    assert!(translated.input().textures.contains_key(&17));
    source.submit(&dynamic(1, 2, &[])).unwrap();
    translated.update(&mut source, anchor).unwrap();
    assert!(!translated.input().textures.contains_key(&17));
    let revision = source.revision();
    let mut old = header(1, 2);
    old[4..8].copy_from_slice(&1_u32.to_le_bytes());
    assert!(source.submit(&old).is_err());
    assert!(source.submit(&header(2, 1)).is_err());
    assert_eq!(source.revision(), revision);
}

#[test]
fn reserved_texture_id_is_never_uploaded_or_retired() {
    let mut source = initialized();
    let revision = source.revision();
    for id in [0, u32::MAX] {
        let mut upload = header(4, 1);
        for value in [id, 1, 1, 0] {
            upload.extend(value.to_le_bytes());
        }
        upload.extend([255; 4]);
        assert!(source.submit(&upload).is_err());
    }
    for id in [0, 1, u32::MAX] {
        let mut retire = header(9, 1);
        for value in [1_u32, 0, id] {
            retire.extend(value.to_le_bytes());
        }
        assert!(source.submit(&retire).is_err());
    }
    assert_eq!(source.revision(), revision);
}
