use prime_scene::{
    protocol::{Frame, MAGIC},
    scene::SourceScene,
};

fn header(op: u32, epoch: u64) -> Vec<u8> {
    let mut bytes = Vec::new();
    for value in [MAGIC, 1, op, 0] {
        bytes.extend(value.to_le_bytes());
    }
    bytes.extend(epoch.to_le_bytes());
    bytes
}
fn mesh(revision: u64, layer: u32) -> Vec<u8> {
    let mut bytes = header(2, 1);
    bytes.extend(91u64.to_le_bytes());
    bytes.extend(revision.to_le_bytes());
    for value in [29_999_984.0_f64, 64.0, -16.0] {
        bytes.extend(value.to_le_bytes());
    }
    for value in [4u32, 28, 0, 12, 16, 4, 0, 0, layer, 0] {
        bytes.extend(value.to_le_bytes());
    }
    for xyz in [
        [0.125_f32, 0.0, 0.0],
        [1.0, 0.0, 0.0],
        [1.0, 1.0, 0.0],
        [0.125, 1.0, 0.0],
    ] {
        for value in xyz {
            bytes.extend(value.to_le_bytes());
        }
        bytes.extend([128, 64, 32, 255]);
        bytes.extend(0.25_f32.to_le_bytes());
        bytes.extend(0.75_f32.to_le_bytes());
        bytes.extend([0, 0, 240, 0]);
    }
    bytes
}
fn initialized() -> SourceScene {
    let mut source = SourceScene::default();
    source.submit(&header(1, 1)).unwrap();
    source
}

#[test]
fn decode_real_block_layout_and_rebase_before_narrowing() {
    let mut source = initialized();
    source.submit(&mesh(1, 0)).unwrap();
    let scene = source.translate([29_999_984.0, 64.0, -16.0]).unwrap();
    assert_eq!(scene.triangle_count(), 2);
    assert_eq!(
        scene.meshes[&(91, 0)].triangles[0].positions[0],
        [0.125, 0.0, 0.0]
    );
    assert_eq!(
        scene.meshes[&(91, 0)].triangles[1].positions,
        [[1.0, 1.0, 0.0], [0.125, 1.0, 0.0], [0.125, 0.0, 0.0]]
    );
    assert_eq!(
        scene.meshes[&(91, 0)].triangles[0].colors[0],
        [128.0 / 255.0, 64.0 / 255.0, 32.0 / 255.0, 1.0]
    );
    assert_eq!(scene.meshes[&(91, 0)].triangles[0].uvs[0], [0.25, 0.75]);
}

#[test]
fn decode_java_source_quads_24_byte_fixture_preserves_every_corner() {
    // Generated by the actual common Java SourceQuads + Packets.mesh encoder:
    // epoch=1, section=91, revision=3, origin=(29999984,64,-16), CUTOUT,
    // ARGB=(ffabcdef,7f123456,01020304,ffffffff), positions/UVs below.
    // A literal packet keeps this test independent of a second Rust wire encoder.
    const PACKET: [u8; 200] = [
        0x50, 0x52, 0x50, 0x54, 0x01, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x5b, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x37,
        0x9c, 0x7c, 0x41, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x50, 0x40, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x30, 0xc0, 0x04, 0x00, 0x00, 0x00, 0x18, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x0c, 0x00, 0x00, 0x00, 0x10, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x01, 0x00,
        0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x3e, 0x00, 0x00, 0x40, 0xc0, 0x00, 0x00, 0x10, 0x41, 0xab, 0xcd, 0xef, 0xff,
        0x00, 0x00, 0x00, 0x3e, 0x00, 0x00, 0x80, 0x3e, 0x00, 0x00, 0x90, 0x3f, 0x00, 0x00, 0x40,
        0xc0, 0x00, 0x00, 0x10, 0x41, 0x12, 0x34, 0x56, 0x7f, 0x00, 0x00, 0x40, 0x3f, 0x00, 0x00,
        0x80, 0x3e, 0x00, 0x00, 0x90, 0x3f, 0x00, 0x00, 0x00, 0xc0, 0x00, 0x00, 0x10, 0x41, 0x02,
        0x03, 0x04, 0x01, 0x00, 0x00, 0x40, 0x3f, 0x00, 0x00, 0x60, 0x3f, 0x00, 0x00, 0x00, 0x3e,
        0x00, 0x00, 0x00, 0xc0, 0x00, 0x00, 0x10, 0x41, 0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00,
        0x3e, 0x00, 0x00, 0x60, 0x3f,
    ];
    let positions = [
        [0.125, -3.0, 9.0],
        [1.125, -3.0, 9.0],
        [1.125, -2.0, 9.0],
        [0.125, -2.0, 9.0],
    ];
    let uvs = [[0.125, 0.25], [0.75, 0.25], [0.75, 0.875], [0.125, 0.875]];
    let rgba = [
        [0xab_u8, 0xcd, 0xef, 0xff],
        [0x12, 0x34, 0x56, 0x7f],
        [0x02, 0x03, 0x04, 0x01],
        [0xff, 0xff, 0xff, 0xff],
    ];

    let mut source = initialized();
    let mut atlas = header(4, 1);
    for value in [1_u32, 1, 1, 0] {
        atlas.extend(value.to_le_bytes());
    }
    atlas.extend([255; 4]);
    source.submit(&atlas).unwrap();
    source.submit(&PACKET).unwrap();
    let scene = source.translate([29_999_728.0, 64.0, -16.0]).unwrap();
    assert_eq!(scene.meshes.len(), 1);
    assert_eq!(scene.triangle_count(), 2);
    let captured = &scene.meshes[&(91, 1)];
    assert_eq!(captured.revision, 3);
    assert_eq!(captured.flags, 1);
    assert_eq!(captured.origin, [256.0, 0.0, 0.0]);
    for (triangle, corners) in captured.triangles.iter().zip([[0, 1, 2], [2, 3, 0]]) {
        assert_eq!(triangle.texture_id, 1);
        assert_eq!(triangle.flags, 1);
        for (corner, source_vertex) in corners.into_iter().enumerate() {
            assert_eq!(triangle.positions[corner], positions[source_vertex]);
            assert_eq!(triangle.uvs[corner], uvs[source_vertex]);
            // Encoded RGB is normalized without EOTF or raster lighting; alpha is independent.
            assert_eq!(
                triangle.colors[corner],
                rgba[source_vertex].map(|channel| f32::from(channel) / 255.0)
            );
        }
    }
}

#[test]
fn every_truncated_mesh_is_rejected_without_publication() {
    let bytes = mesh(2, 0);
    let mut source = initialized();
    source.submit(&mesh(1, 0)).unwrap();
    let revision = source.revision;
    for length in 0..bytes.len() {
        assert!(
            source.submit(&bytes[..length]).is_err(),
            "accepted prefix {length}"
        );
        assert_eq!(source.revision, revision);
    }
    assert_eq!(
        source
            .translate([29_999_984.0, 64.0, -16.0])
            .unwrap()
            .triangle_count(),
        2
    );
}

#[test]
fn malformed_input_cannot_partially_replace_geometry() {
    let mut source = initialized();
    source.submit(&mesh(1, 0)).unwrap();
    for (offset, value) in [
        (104, f32::NAN.to_bits()),
        (68, 0u32),
        (64, u32::MAX),
        (92, 2u32),
    ] {
        let mut bytes = mesh(2, 0);
        bytes[offset..offset + 4].copy_from_slice(&value.to_le_bytes());
        assert!(source.submit(&bytes).is_err());
    }
    assert_eq!(source.revision, 2);
}

#[test]
fn section_tombstone_prevents_resurrection_of_any_layer() {
    let mut source = initialized();
    source.submit(&mesh(1, 0)).unwrap();
    let mut remove = header(3, 1);
    remove.extend(91u64.to_le_bytes());
    remove.extend(3u64.to_le_bytes());
    source.submit(&remove).unwrap();
    assert!(source.submit(&mesh(2, 1)).is_err());
    source.submit(&mesh(4, 0)).unwrap();
    source.submit(&mesh(4, 1)).unwrap();
    assert!(source.submit(&remove).is_err());
    assert!(source.submit(&mesh(4, 0)).is_err());
    source.submit(&header(1, 2)).unwrap();
    assert!(source.submit(&mesh(5, 0)).is_err());
    assert!(source.translate([0.0; 3]).unwrap().meshes.is_empty());
}

#[test]
fn texture_length_and_identity_are_checked() {
    let mut source = initialized();
    let mut bytes = header(4, 1);
    for value in [1u32, 1, 1, 0] {
        bytes.extend(value.to_le_bytes());
    }
    bytes.extend([20, 40, 80, 128]);
    source.submit(&bytes).unwrap();
    let scene = source.translate([0.0; 3]).unwrap();
    assert_eq!(scene.textures[&1].pixels.as_ref(), &[20, 40, 80, 128]);
    bytes.push(0);
    assert!(source.submit(&bytes).is_err());
    assert_eq!(source.revision, 2);
}

#[test]
fn snapshots_share_immutable_vertices_across_rebases_and_keep_old_versions_alive() {
    let mut source = initialized();
    source.submit(&mesh(1, 0)).unwrap();
    let first = source.translate([29_999_984.0, 64.0, -16.0]).unwrap();
    let shifted = source.translate([29_999_728.0, 64.0, -16.0]).unwrap();
    assert!(std::sync::Arc::ptr_eq(
        &first.meshes[&(91, 0)].triangles,
        &shifted.meshes[&(91, 0)].triangles
    ));
    assert_eq!(shifted.meshes[&(91, 0)].origin, [256.0, 0.0, 0.0]);
    let mut changed = mesh(2, 0);
    changed[104..108].copy_from_slice(&0.5_f32.to_le_bytes());
    source.submit(&changed).unwrap();
    let latest = source.translate([29_999_984.0, 64.0, -16.0]).unwrap();
    assert_eq!(first.meshes[&(91, 0)].triangles[0].positions[0][0], 0.125);
    assert_eq!(latest.meshes[&(91, 0)].triangles[0].positions[0][0], 0.5);
}

#[test]
fn absent_section_removal_preserves_render_revision_but_blocks_stale_geometry() {
    let mut source = initialized();
    let revision = source.revision;
    let mut remove = header(3, 1);
    remove.extend(91u64.to_le_bytes());
    remove.extend(3u64.to_le_bytes());
    source.submit(&remove).unwrap();
    assert_eq!(source.revision, revision);
    assert!(source.submit(&mesh(2, 0)).is_err());
    source.submit(&mesh(4, 0)).unwrap();
    assert_eq!(
        source
            .translate([29_999_984.0, 64.0, -16.0])
            .unwrap()
            .triangle_count(),
        2
    );
}

#[test]
fn frame_rejects_non_orthogonal_camera_and_invalid_extent() {
    let mut bytes = header(5, 1);
    for value in [30_000_000.0_f64, 70.0, -10.0] {
        bytes.extend(value.to_le_bytes());
    }
    for value in [0.0_f32, 0.0, -1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0] {
        bytes.extend(value.to_le_bytes());
    }
    for value in [640u32, 360, 0, 0] {
        bytes.extend(value.to_le_bytes());
    }
    let frame = Frame::parse(&bytes).unwrap();
    assert_eq!(frame.output_len(), 640 * 360 * 4);
    assert_eq!(
        frame.relative_camera(frame.anchor()).position,
        [128.0, 70.0, 246.0]
    );
    bytes[88..92].copy_from_slice(&u32::MAX.to_le_bytes());
    assert!(Frame::parse(&bytes).is_err());
    bytes[88..92].copy_from_slice(&640u32.to_le_bytes());
    bytes[60..64].copy_from_slice(&0.0_f32.to_le_bytes());
    assert!(Frame::parse(&bytes).is_err());
}
